export const hxlRetailFixtures = [
  {name:"何家铺好想来超市",type:"购物服务;便民商店/便利店;便民商店/便利店",tag:"便利店",expected:"接受"},
  {name:"兴隆·好想来省钱超市",type:"购物服务",tag:"便利店",expected:"接受"},
  {name:"常平好想来优选零食店",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来官方",type:"购物服务;购物相关场所;购物相关场所",expected:"排除"},
  {name:"好想来奶站",tag:"零食",expected:"排除"},
  {name:"何家铺好想来奶站(中心店)",tag:"便利店",expected:"排除"},
  {name:"好想来神秘后缀",type:"购物服务",expected:"待核实"},
  {name:"好想来旅游服务店",type:"购物服务",expected:"待核实"},
  {name:"好想来科技馆",type:"餐饮服务",expected:"待核实"},
  {name:"好想来(奶站旁店)",type:"购物服务",expected:"接受"},
  {name:"好想来(官方路店)",type:"购物服务",expected:"接受"},
  {name:"好想来零食乐园大连甘井子区大连工业大学(南苑宿舍区)店",tag:"零食",expected:"接受"},
  {name:"好想来零食工厂(商丘团结路店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"兴隆好想来",type:"餐饮服务;餐饮相关场所;餐饮相关",expected:"接受"},
  {name:"易旺好想来零食店",type:"购物服务",tag:"日杂店",expected:"排除"},
  {name:"好想来副食品店",type:"购物服务",tag:"零食",expected:"排除"},
  {name:"兴隆好想来(暂停营业)",type:"购物服务",expected:"排除"},
  {name:"兴隆好想来(南宁仓)",type:"购物服务",expected:"排除"},
  {name:"兴隆好想来",type:"购物服务",tag:"按摩",expected:"排除"},
  {name:"好想来体验馆",type:"购物服务",tag:"保健;桌游",expected:"待核实"},
  {name:"其他店铺(好想来旁)",type:"购物服务",tag:"零食",expected:"待核实"},
  {name:"好想来零食工厂(商丘团结路店)",expected:"待核实"},
  {name:"好想来(店)",type:"购物服务",expected:"待核实"},
  {name:"好想来(中心店)足浴",type:"购物服务",expected:"待核实"},
  {name:"来优品好想来零食(和平东路店)",type:"购物服务",expected:"待核实"},
  {name:"好想来品牌乐园(菏泽郓城随官屯镇二店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来大连旅顺口区科技学院店",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来省钱超市好想来省钱(岳阳平江县天岳汽车站店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来购物中心",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来购物中心(珠江东路店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来零食乐园 (石家庄栾城区西营店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来零食可乐园(威海环翠区智慧谷T16街区店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来零食小镇(春晖苑店)",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来零食屋",type:"购物服务",tag:"零食",expected:"接受"},
  {name:"好想来露",type:"购物服务",expected:"待核实"},
  {name:"好想来零食乐园 空港澜庭店",tag:"零食",expected:"接受"},
  {name:"好想来零食乐园湖西职业教育园店",tag:"零食",expected:"接受"},
] as const;
