"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import type {EChartsType} from "echarts/core";
import {DASHBOARD_PROVINCES,UNKNOWN_PROVINCE,filterDashboard,shortProvince,type BrandDashboardSnapshot,type DashboardMatrixRow} from "../shared/brand-dashboard";
import {formatBeijingDateTime} from "./time";
import "./brand-dashboard.css";

type Request=<T>(path:string,init?:RequestInit)=>Promise<T>;
const colors=["#246BFD","#F97345","#16A085","#B98B14","#7C5CFC","#E94F86","#17A2B8","#78943E","#D65DB1","#008F7A","#C97A22","#536DFE","#EF476F"];
const number=(value:number)=>value.toLocaleString("zh-CN");

function DashboardCharts({matrix,brands,allBrands,selected,onSelect,showAll,onReady}:{matrix:DashboardMatrixRow[];brands:string[];allBrands:string[];selected:string|null;onSelect:(province:string|null)=>void;showAll:boolean;onReady:(ready:boolean)=>void}){
  const mapRef=useRef<HTMLDivElement>(null),barRef=useRef<HTMLDivElement>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0);
  useEffect(()=>{
    let disposed=false,map:EChartsType|undefined,bar:EChartsType|undefined,observer:ResizeObserver|undefined;
    const controller=new AbortController();onReady(false);setError("");
    void Promise.all([import("./brand-dashboard-charts"),fetch("/maps/china-provinces.geojson",{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error("省级地图加载失败");return response.json()})]).then(([{echarts},geo])=>{
      if(disposed||!mapRef.current||!barRef.current)return;
      if(!echarts.getMap("brand-library-china"))echarts.registerMap("brand-library-china",geo);
      map=echarts.init(mapRef.current);bar=echarts.init(barRef.current);
      const lookup=new Map(matrix.map(row=>[row.province,row])),provinceRows=matrix.filter(row=>row.province!==UNKNOWN_PROVINCE),max=Math.max(1,...provinceRows.map(row=>row.total));
      const description=(province:string)=>{const row=lookup.get(province);if(!row)return `${province}\n未选中`;return `${province}  ${number(row.total)} 家\n`+brands.filter(brand=>row.brands[brand]>0).sort((a,b)=>row.brands[b]-row.brands[a]).map(brand=>`${brand}：${number(row.brands[brand])}`).join("\n")};
      map.setOption({animation:false,tooltip:{trigger:"item",renderMode:"richText",confine:true,formatter:(item:{name:string})=>description(item.name)},visualMap:{min:0,max,left:18,bottom:10,orient:"horizontal",text:[`${number(max)} 家`,"0"],inRange:{color:["#eaf1ff","#b8ccff","#77a3ff","#3e79f2","#173e99"]},textStyle:{color:"#61728b",fontSize:11}},series:[{type:"map",map:"brand-library-china",roam:true,scaleLimit:{min:.85,max:4},layoutCenter:["50%","46%"],layoutSize:"93%",selectedMode:"single",label:{show:true,fontSize:9,lineHeight:13,color:"#253752",textBorderColor:"#ffffff",textBorderWidth:2,formatter:(item:{name:string})=>item.name?`${shortProvince(item.name)}\n${lookup.has(item.name)?number(lookup.get(item.name)!.total)+"家":"未选中"}`:""},itemStyle:{borderColor:"#fff",borderWidth:1,areaColor:"#edf0f5"},emphasis:{itemStyle:{areaColor:"#f8be4f"}},select:{itemStyle:{areaColor:"#f8be4f",borderColor:"#df9a22",borderWidth:2}},data:DASHBOARD_PROVINCES.map(province=>({name:province,value:lookup.get(province)?.total??null,selected:province===selected}))}]});
      const ranked=[...matrix].sort((a,b)=>b.total-a.total||a.province.localeCompare(b.province,"zh-CN"));
      bar.setOption({animation:false,grid:{left:80,right:68,top:16,bottom:35},tooltip:{trigger:"axis",renderMode:"richText",confine:true,formatter:(items:Array<{name:string}>)=>description(items[0]?.name||"")},xAxis:{type:"value",axisLabel:{color:"#77849a"},splitLine:{lineStyle:{color:"#edf0f4",type:"dashed"}}},yAxis:{type:"category",inverse:true,data:ranked.map(row=>row.province),axisLabel:{formatter:shortProvince,color:"#506079",fontSize:11},axisLine:{show:false},axisTick:{show:false}},dataZoom:!showAll&&ranked.length>14?[{type:"slider",yAxisIndex:0,right:4,width:10,startValue:0,endValue:13,filterMode:"filter"},{type:"inside",yAxisIndex:0,startValue:0,endValue:13}]:[],series:[...brands.map(brand=>({name:brand,type:"bar",stack:"stores",barWidth:17,label:{show:true,position:"inside",color:"#fff",fontSize:10,formatter:(item:{value:unknown})=>Number(item.value)>=Math.max(10,max/40)?number(Number(item.value)):""},itemStyle:{color:colors[allBrands.indexOf(brand)%colors.length]},emphasis:{focus:"series"},data:ranked.map(row=>({value:row.brands[brand]||0,itemStyle:row.province===selected?{borderColor:"#172b4d",borderWidth:1}:undefined}))})),{name:"总计",type:"bar",barGap:"-100%",barWidth:17,silent:true,itemStyle:{color:"transparent"},tooltip:{show:false},label:{show:true,position:"right",color:"#253752",fontSize:11,formatter:(item:{value:unknown})=>number(Number(item.value))},data:ranked.map(row=>row.total)}]});
      for(const chart of [map,bar])chart.on("click",(event)=>{const name=String(event.name||"");if(lookup.has(name))onSelect(name===selected?null:name)});
      observer=new ResizeObserver(()=>{map?.resize();bar?.resize()});observer.observe(mapRef.current);observer.observe(barRef.current);onReady(true);
    }).catch(error=>{if(!disposed)setError(error instanceof Error?error.message:"图表加载失败")});
    return()=>{disposed=true;controller.abort();observer?.disconnect();map?.dispose();bar?.dispose();onReady(false)};
  },[matrix,brands,allBrands,selected,onSelect,showAll,retry,onReady]);
  return <>{error&&<p className="bd-warning" role="alert">{error}，可查看下方数量明细。<button onClick={()=>setRetry(v=>v+1)}>重试图表</button></p>}<div className="bd-visual-grid">
    <section className="bd-chart-panel"><div className="bd-panel-heading"><div><small>GEOGRAPHIC DISTRIBUTION</small><h3>省级门店热力分布</h3></div><span>颜色越深，门店越多</span></div><div className="bd-map" ref={mapRef} role="img" aria-label="中国省级门店数量热力地图，点击省份查看品牌明细"/></section>
    <section className="bd-chart-panel"><div className="bd-panel-heading"><div><small>BRAND MIX BY PROVINCE</small><h3>各省品牌结构</h3></div><span>按总数排序 · 点击查看明细</span></div><div className="bd-bar" style={showAll?{height:Math.max(520,matrix.length*30+55)}:undefined} ref={barRef} role="img" aria-label="各省品牌门店数量堆叠条形图"/></section>
  </div></>;
}

export default function BrandDashboard({request,isAdmin,onViewStores}:{request:Request;isAdmin:boolean;onViewStores:(province:string,brands:string[])=>void}){
  const [data,setData]=useState<BrandDashboardSnapshot|null>(null),[brands,setBrands]=useState<string[]>([]),[provinces,setProvinces]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[search,setSearch]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[showFilters,setShowFilters]=useState(false),[showAll,setShowAll]=useState(false),[exporting,setExporting]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
  const root=useRef<HTMLDivElement>(null),previousSnapshot=useRef<BrandDashboardSnapshot|null>(null),alive=useRef(true);
  const apply=useCallback((next:BrandDashboardSnapshot)=>{const previous=previousSnapshot.current;if(previous?.generatedAt===next.generatedAt&&previous.stale===next.stale&&previous.message===next.message)return;setData(next);setBrands(current=>!previous||(current.length===previous.brands.length&&previous.brands.every(brand=>current.includes(brand)))?next.brands:current.filter(brand=>next.brands.includes(brand)));setProvinces(current=>!previous||(current.length===previous.provinces.length&&previous.provinces.every(province=>current.includes(province)))?next.provinces:current.filter(province=>next.provinces.includes(province)));previousSnapshot.current=next},[]);
  const load=useCallback(async(signal?:AbortSignal)=>{try{const result=await request<BrandDashboardSnapshot>("/brand-library/dashboard",{signal});if(!signal?.aborted&&alive.current){apply(result);setError("")}}catch(error){if(!signal?.aborted&&alive.current)setError(error instanceof Error?error.message:"门店看板加载失败")}finally{if(!signal?.aborted&&alive.current)setLoading(false)}},[request,apply]);
  useEffect(()=>{alive.current=true;const controller=new AbortController();void load(controller.signal);const timer=window.setInterval(()=>void load(controller.signal),60000);return()=>{alive.current=false;controller.abort();window.clearInterval(timer)}},[load]);
  const filtered=useMemo(()=>data?filterDashboard(data,brands,provinces):null,[data,brands,provinces]);
  const focus=filtered?.matrix.find(row=>row.province===selected);
  function reset(){if(data){setBrands(data.brands);setProvinces(data.provinces);setSelected(null);setSearch("")}}
  async function refresh(){setRefreshing(true);setError("");try{apply(await request<BrandDashboardSnapshot>("/admin/brand-library/dashboard/refresh",{method:"POST",body:"{}"}));setNotice("已按当前品牌门店库更新看板。") }catch(error){setError(error instanceof Error?error.message:"更新失败，已保留上次统计")}finally{setRefreshing(false)}}
  async function exportPng(){if(!root.current||!ready)return;setExporting(true);setNotice("");try{const {default:html2canvas}=await import("html2canvas");const canvas=await html2canvas(root.current,{scale:2,backgroundColor:"#f3f6fb",useCORS:true,ignoreElements:element=>element.hasAttribute("data-bd-no-export")});const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("图片生成失败")),"image/png"));const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`门店看板_${new Date().toISOString().slice(0,10)}.png`;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("高清 PNG 已生成。") }catch(error){setError(error instanceof Error?error.message:"图片导出失败，请重试")}finally{setExporting(false)}}
  if(!data)return <section className="panel" aria-busy={loading}><h2>门店看板</h2>{error?<p role="alert">{error} <button onClick={()=>{setLoading(true);void load()}}>重试</button></p>:<p role="status">正在汇总品牌门店库数据…</p>}</section>;
  return <div className="brand-dashboard" ref={root}>
    <header className="bd-heading"><div><small>STORE NETWORK INTELLIGENCE</small><h2>门店看板</h2><p>全国门店数量分布 · 数据来自共享品牌门店库</p></div><div className="bd-actions"><div className="bd-sync"><b>{data.stale?"统计待更新":"品牌门店库已同步"}</b><small>更新于 {formatBeijingDateTime(data.generatedAt)}</small></div><div data-bd-no-export>{isAdmin&&<button disabled={refreshing} onClick={refresh}>{refreshing?"更新中…":"立即更新"}</button>}<button disabled={exporting||!ready} onClick={exportPng}>{exporting?"正在导出…":"导出高清 PNG"}</button></div></div></header>
    {(error||data.message)&&<p className="bd-warning" role="alert">{error||data.message}</p>}{notice&&<p className="bd-notice" role="status" data-bd-no-export>{notice}</p>}
    <div className="bd-kpis">{[["当前门店总数",filtered!.total,"家","当前品牌与省份筛选范围"],["已覆盖省份",filtered!.covered,"个","含港澳台共 34 个区域"],["覆盖品牌",filtered!.brandCount,"个","有门店数据的品牌"],["省份待补全",filtered!.unknown,"家","计入总数，暂不落入省级地图"]].map(([label,value,unit,note],index)=><article key={String(label)} style={{borderTopColor:colors[index]}}><span>{label}</span><strong>{number(Number(value))}<small>{unit}</small></strong><p>{note}</p></article>)}</div>
    <div className="bd-filter-bar" data-bd-no-export><input value={search} onChange={event=>{setSearch(event.target.value);setShowFilters(true)}} placeholder="搜索看板品牌"/><button onClick={()=>setShowFilters(value=>!value)}>筛选：品牌 {brands.length}/{data.brands.length} · 省份 {provinces.length}/{data.provinces.length}</button><button onClick={reset}>重置筛选</button><label><input type="checkbox" checked={showAll} onChange={event=>setShowAll(event.target.checked)}/> 展开全部省份（导出长图）</label></div>
    {showFilters&&<div className="bd-filter-drawer" data-bd-no-export><fieldset><legend>品牌多选</legend><div><button onClick={()=>setBrands(data.brands)}>全选品牌</button><button onClick={()=>setBrands([])}>清空品牌</button></div>{data.brands.filter(brand=>brand.includes(search.trim())).map(brand=><label key={brand}><input type="checkbox" checked={brands.includes(brand)} onChange={()=>setBrands(current=>current.includes(brand)?current.filter(value=>value!==brand):[...current,brand])}/>{brand}</label>)}</fieldset><fieldset><legend>省份多选</legend><div><button onClick={()=>setProvinces(data.provinces)}>全选省份</button><button onClick={()=>setProvinces([])}>清空省份</button></div>{data.provinces.map(province=><label key={province}><input type="checkbox" checked={provinces.includes(province)} onChange={()=>{setSelected(null);setProvinces(current=>current.includes(province)?current.filter(value=>value!==province):[...current,province])}}/>{shortProvince(province)}</label>)}</fieldset></div>}
    <div className="bd-legend" aria-label="看板品牌图例">{data.brands.map((brand,index)=><button key={brand} aria-pressed={brands.includes(brand)} className={brands.includes(brand)?"":"off"} onClick={()=>setBrands(current=>current.includes(brand)?current.filter(value=>value!==brand):[...current,brand])}><i style={{background:colors[index%colors.length]}}/>{brand}</button>)}</div>
    {!filtered!.total&&<div className="bd-empty" role="status">{data.total?"当前筛选没有门店，请调整品牌或省份。":"品牌门店库暂无可统计门店。门店入库后会在每日更新时显示，管理员也可点击立即更新。"}</div>}
    <DashboardCharts matrix={filtered!.matrix} brands={brands} allBrands={data.brands} selected={selected} onSelect={setSelected} showAll={showAll} onReady={setReady}/>
    {focus&&<section className="bd-focus"><div className="bd-panel-heading"><h3>{focus.province} · {number(focus.total)} 家门店</h3><button onClick={()=>setSelected(null)}>收起明细</button></div><div className="bd-focus-brands">{Object.entries(focus.brands).filter(([,count])=>count>0).sort((a,b)=>b[1]-a[1]).map(([brand,count])=><span key={brand}>{brand}<b>{number(count)} 家</b></span>)}</div>{focus.province!==UNKNOWN_PROVINCE&&focus.total>0&&<button data-bd-no-export onClick={()=>onViewStores(focus.province,brands)}>查看该省门店明细</button>}</section>}
    <details className="bd-details" data-bd-no-export><summary>查看省份数量明细</summary><div className="table-wrap"><table><thead><tr><th>省份</th><th>门店总数</th><th>覆盖品牌</th><th>操作</th></tr></thead><tbody>{[...filtered!.matrix].sort((a,b)=>b.total-a.total).map(row=><tr key={row.province}><td>{row.province}</td><td>{number(row.total)}</td><td>{Object.values(row.brands).filter(count=>count>0).length}</td><td><button onClick={()=>setSelected(row.province)}>查看品牌结构</button>{row.total>0&&row.province!==UNKNOWN_PROVINCE&&<button onClick={()=>onViewStores(row.province,brands)}>查看门店</button>}</td></tr>)}</tbody></table></div></details>
    <footer className="bd-footnote">统计口径：每家有效门店计 1 家；包含标签待核验门店，排除管理员已删除及明确无关记录。数据来源：共享品牌门店库。<br/>每日北京时间 02:00 自动汇总 · 下次更新 {formatBeijingDateTime(data.nextRefreshAt)} · 门店库入库/更新由现有查询任务负责。</footer>
  </div>;
}
