/* eslint-disable @typescript-eslint/no-explicit-any */
import ExcelJS from "exceljs";
import fs from "node:fs/promises";
import path from "node:path";
import { query } from "./db.js";
import { amapRequest, clean, discoverBrandStores, POI_CATEGORY_TYPES, type Poi, type Row } from "./services.js";

export const PROVINCES=["北京市","天津市","河北省","山西省","内蒙古自治区","辽宁省","吉林省","黑龙江省","上海市","江苏省","浙江省","安徽省","福建省","江西省","山东省","河南省","湖北省","湖南省","广东省","广西壮族自治区","海南省","重庆市","四川省","贵州省","云南省","西藏自治区","陕西省","甘肃省","青海省","宁夏回族自治区","新疆维吾尔自治区"];
export const DEFAULT_BRANDS=[
  {name:"零食很忙",aliases:["零食很忙"]},{name:"零食有鸣",aliases:["零食有鸣"]},{name:"赵一鸣零食",aliases:["赵一鸣零食","赵一鸣"]},
  {name:"好想来零食",aliases:["好想来零食乐园","好想来品牌零食","好想来零食","好想来","好像来"]},{name:"爱零食",aliases:["爱零食"]},
  {name:"来优品",aliases:["来优品"]},{name:"戴永红",aliases:["戴永红"]},{name:"糖巢",aliases:["糖巢"]},{name:"老婆大人",aliases:["老婆大人"]},
  {name:"良品铺子",aliases:["良品铺子"]},{name:"来伊份",aliases:["来伊份"]},
];

const uniqueStrings=(value:unknown)=>[...new Set((Array.isArray(value)?value:[]).map(clean).filter(Boolean))];
const normalizeStatus=(value:unknown)=>["正常","新增","更新","疑似关闭","数据异常"].includes(clean(value))?clean(value):"";

export async function ensureDefaultBrands(tenantId:number,userId:number){
  for(const brand of DEFAULT_BRANDS)await query("INSERT INTO brand_catalog(tenant_id,standard_name,aliases_json,approval_status,created_by) VALUES($1,$2,$3,'approved',$4) ON CONFLICT(tenant_id,standard_name) DO NOTHING",[tenantId,brand.name,JSON.stringify(brand.aliases),userId]);
}

export async function listBrands(tenantId:number,userId:number){await ensureDefaultBrands(tenantId,userId);return (await query<Row>("SELECT id,standard_name,aliases_json,approval_status,active,created_at,updated_at FROM brand_catalog WHERE tenant_id=$1 AND active=TRUE ORDER BY approval_status,standard_name",[tenantId])).rows.map(row=>({id:Number(row.id),name:row.standard_name,aliases:row.aliases_json||[],status:row.approval_status,active:row.active,created_at:row.created_at,updated_at:row.updated_at}))}

export async function addPendingBrands(tenantId:number,userId:number,names:string[]){for(const name of uniqueStrings(names)){if(DEFAULT_BRANDS.some(item=>item.name===name))continue;await query("INSERT INTO brand_catalog(tenant_id,standard_name,aliases_json,approval_status,created_by) VALUES($1,$2,$3,'pending',$4) ON CONFLICT(tenant_id,standard_name) DO NOTHING",[tenantId,name,JSON.stringify([name]),userId])}}

export async function listProvinceCities(province:string){
  if(["北京市","天津市","上海市","重庆市"].includes(province))return [{name:province,adcode:""}];
  const data=await amapRequest("/v3/config/district",{keywords:province,subdistrict:1,extensions:"base"}),roots=Array.isArray(data.districts)?data.districts:[],children=roots.length&&Array.isArray(roots[0]?.districts)?roots[0].districts:[];
  return children.map((item:Row)=>({name:clean(item.name),adcode:clean(item.adcode)})).filter((item:{name:string})=>item.name);
}

export function serializeDiscoveryJob(row:Row){const total=Number(row.total_units||0),processed=Number(row.processed_units||0);return {id:Number(row.id),province:row.province,cities:row.cities_json||[],brands:row.brands_json||[],status:row.status,control:row.control,total_units:total,processed_units:processed,progress_percent:Math.round(processed/Math.max(1,total)*100),found_stores:Number(row.found_stores||0),api_calls:Number(row.api_calls||0),cached_units:Number(row.cached_units||0),current_region:row.current_region||"",error_message:row.error_message||"",force_refresh:Boolean(row.force_refresh),created_by:Number(row.created_by),created_at:row.created_at,updated_at:row.updated_at,completed_at:row.completed_at||null}}

export async function createDiscoveryJob(tenantId:number,userId:number,input:Row){
  const province=clean(input.province),brands=uniqueStrings(input.brands),cities=uniqueStrings(input.cities);if(!PROVINCES.includes(province))throw new Error("请选择有效省份");if(!brands.length)throw new Error("请至少选择一个品牌");if(brands.length>30)throw new Error("单次最多查询30个品牌");await addPendingBrands(tenantId,userId,brands);
  const row=(await query<Row>("INSERT INTO brand_discovery_jobs(tenant_id,created_by,province,cities_json,brands_json,force_refresh,status,control) VALUES($1,$2,$3,$4,$5,$6,'等待执行','run') RETURNING *",[tenantId,userId,province,JSON.stringify(cities),JSON.stringify(brands),Boolean(input.force_refresh)])).rows[0];return serializeDiscoveryJob(row);
}

class QuotaPauseError extends Error{}
export async function consumeBackgroundQuota(tenantId:number){const limit=Math.max(1,Number(process.env.AMAP_DAILY_LIMIT||2000)),backgroundLimit=Math.max(1,Math.floor(limit*.9)),result=await query<Row>("INSERT INTO amap_usage_daily(tenant_id,usage_date,used_calls) VALUES($1,CURRENT_DATE,1) ON CONFLICT(tenant_id,usage_date) DO UPDATE SET used_calls=amap_usage_daily.used_calls+1,updated_at=NOW() WHERE amap_usage_daily.used_calls<$2 RETURNING used_calls",[tenantId,backgroundLimit]);if(!result.rowCount)throw new QuotaPauseError("今日高德后台任务额度已达到90%，任务已自动暂停");return {used:Number(result.rows[0].used_calls),limit,background_limit:backgroundLimit,remaining:Math.max(0,limit-Number(result.rows[0].used_calls))}}
export const isQuotaPauseError=(error:unknown)=>error instanceof QuotaPauseError;
export function quotaResumeDelay(){const now=new Date(),beijing=new Date(now.getTime()+8*3600_000),nextUtc=Date.UTC(beijing.getUTCFullYear(),beijing.getUTCMonth(),beijing.getUTCDate()+1,0,5)-8*3600_000;return Math.max(60_000,nextUtc-now.getTime())}
async function scheduleDiscoveryResume(jobId:number,tenantId:number,userId:number){const {taskQueue}=await import("./queue.js");await taskQueue.add("discover-brand-stores",{jobId,tenantId,userId},{attempts:1,delay:quotaResumeDelay()})}
export async function usageSummary(tenantId:number){const limit=Math.max(1,Number(process.env.AMAP_DAILY_LIMIT||2000)),used=Number((await query<Row>("SELECT used_calls FROM amap_usage_daily WHERE tenant_id=$1 AND usage_date=CURRENT_DATE",[tenantId])).rows[0]?.used_calls||0);return {limit,used,remaining:Math.max(0,limit-used),background_limit:Math.floor(limit*.9),reserve:Math.ceil(limit*.1),percent:Math.round(used/limit*100)}}

export async function cleanupBrandLibraryRetention(tenantId:number){
  const expired=(await query<Row>("SELECT id,file_path FROM brand_export_jobs WHERE tenant_id=$1 AND file_expires_at<=NOW()",[tenantId])).rows;
  for(const item of expired)if(item.file_path)await fs.rm(String(item.file_path),{force:true}).catch(()=>undefined);
  await query("DELETE FROM brand_export_jobs WHERE tenant_id=$1 AND file_expires_at<=NOW()",[tenantId]);
  await query("DELETE FROM brand_discovery_jobs WHERE tenant_id=$1 AND COALESCE(completed_at,updated_at)<NOW()-INTERVAL '180 days' AND status NOT IN ('等待执行','正在读取区域','正在查询','等待继续','额度暂停')",[tenantId]);
  await query("DELETE FROM jobs WHERE tenant_id=$1 AND config_json->>'source'='brand_library' AND updated_at<NOW()-INTERVAL '180 days' AND control='idle'",[tenantId]);
  return {expired_exports:expired.length};
}

async function saveDiscoveredStores(tenantId:number,jobId:number,brand:string,province:string,city:string,stores:Row[],complete:boolean){
  const seen:string[]=[];
  for(const store of stores){const uid=clean(store.id)||`${brand}|${clean(store.name)}|${Array.isArray(store.location)?store.location.join(","):""}`,location=Array.isArray(store.location)?store.location:[null,null];if(!uid||location[0]==null||location[1]==null)continue;seen.push(uid);await query("INSERT INTO brand_stores(tenant_id,brand_name,source_uid,amap_poi_id,amap_name,province,city,district,address,longitude,latitude,poi_type,typecode,data_status,raw_json,last_job_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'新增',$14,$15) ON CONFLICT(tenant_id,source_uid) DO UPDATE SET brand_name=EXCLUDED.brand_name,amap_poi_id=EXCLUDED.amap_poi_id,amap_name=EXCLUDED.amap_name,province=EXCLUDED.province,city=EXCLUDED.city,district=EXCLUDED.district,address=EXCLUDED.address,longitude=EXCLUDED.longitude,latitude=EXCLUDED.latitude,poi_type=EXCLUDED.poi_type,typecode=EXCLUDED.typecode,data_status=CASE WHEN brand_stores.amap_name IS DISTINCT FROM EXCLUDED.amap_name OR brand_stores.address IS DISTINCT FROM EXCLUDED.address OR brand_stores.longitude IS DISTINCT FROM EXCLUDED.longitude OR brand_stores.latitude IS DISTINCT FROM EXCLUDED.latitude THEN '更新' ELSE '正常' END,raw_json=EXCLUDED.raw_json,last_job_id=EXCLUDED.last_job_id,last_seen_at=NOW(),updated_at=NOW()",[tenantId,brand,uid,clean(store.id),clean(store.name),clean(store.province)||province,clean(store.city)||city,clean(store.district),clean(store.address),Number(location[0]),Number(location[1]),clean(store.type),clean(store.typecode),JSON.stringify(store),jobId])}
  if(complete)await query("UPDATE brand_stores SET data_status='疑似关闭',updated_at=NOW() WHERE tenant_id=$1 AND brand_name=$2 AND province=$3 AND city=$4 AND last_job_id IS DISTINCT FROM $5 AND data_status<>'数据异常'",[tenantId,brand,province,city,jobId]);
  await query("INSERT INTO brand_region_cache(tenant_id,brand_name,province,city,store_count,complete,refreshed_at) VALUES($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT(tenant_id,brand_name,province,city) DO UPDATE SET store_count=EXCLUDED.store_count,complete=EXCLUDED.complete,refreshed_at=NOW()",[tenantId,brand,province,city,seen.length,complete]);
}

export async function processDiscoveryJob(jobId:number,tenantId:number,userId:number){
  let record=(await query<Row>("SELECT * FROM brand_discovery_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows[0];if(!record)throw new Error("品牌查询任务不存在");if(record.control==="pause"&&record.status==="已暂停")return;let cities=uniqueStrings(record.cities_json),apiCalls=Number(record.api_calls||0);const errors:string[]=[];
  await query("UPDATE brand_discovery_jobs SET status='正在读取区域',started_at=COALESCE(started_at,NOW()),updated_at=NOW() WHERE id=$1",[jobId]);
  if(!cities.length){try{await consumeBackgroundQuota(tenantId);apiCalls++;cities=(await listProvinceCities(record.province)).map((item:{name:string;adcode:string})=>item.name)}catch(error){if(error instanceof QuotaPauseError){await query("UPDATE brand_discovery_jobs SET status='额度暂停',control='auto',api_calls=$1,error_message=$2,updated_at=NOW() WHERE id=$3",[apiCalls,error.message,jobId]);await scheduleDiscoveryResume(jobId,tenantId,userId);return}throw error}}
  if(!cities.length)cities=[clean(record.province)];const brands=uniqueStrings(record.brands_json),catalog=(await query<Row>("SELECT standard_name,aliases_json FROM brand_catalog WHERE tenant_id=$1 AND standard_name=ANY($2::text[])",[tenantId,brands])).rows,brandAliases=new Map(catalog.map(item=>[clean(item.standard_name),uniqueStrings(item.aliases_json)])),total=cities.length*brands.length;await query("UPDATE brand_discovery_jobs SET cities_json=$1,total_units=$2,processed_units=0,cached_units=0,status='正在查询',control='run',api_calls=$3,updated_at=NOW() WHERE id=$4",[JSON.stringify(cities),total,apiCalls,jobId]);
  for(const city of cities)for(const brand of brands){record=(await query<Row>("SELECT * FROM brand_discovery_jobs WHERE id=$1",[jobId])).rows[0];if(record.control!=="run")return;const current=`${city} · ${brand}`;await query("UPDATE brand_discovery_jobs SET current_region=$1,updated_at=NOW() WHERE id=$2",[current,jobId]);const cache=(await query<Row>("SELECT * FROM brand_region_cache WHERE tenant_id=$1 AND brand_name=$2 AND province=$3 AND city=$4 AND complete=TRUE AND refreshed_at>NOW()-INTERVAL '30 days'",[tenantId,brand,record.province,city])).rows[0];if(cache&&!record.force_refresh){await query("UPDATE brand_discovery_jobs SET processed_units=processed_units+1,cached_units=cached_units+1,found_stores=(SELECT COUNT(*) FROM brand_stores WHERE tenant_id=$1 AND brand_name=ANY($2::text[]) AND province=$3),updated_at=NOW() WHERE id=$4",[tenantId,brands,record.province,jobId]);continue}
    let unitCalls=0;try{const result=await discoverBrandStores(brand,city,"",async(path,params)=>{await consumeBackgroundQuota(tenantId);unitCalls++;return amapRequest(path,params)},brandAliases.get(brand)||[brand]);apiCalls+=unitCalls;await saveDiscoveredStores(tenantId,jobId,brand,record.province,city,result.stores,result.complete);await query("UPDATE brand_discovery_jobs SET processed_units=processed_units+1,api_calls=$1,found_stores=(SELECT COUNT(*) FROM brand_stores WHERE tenant_id=$2 AND brand_name=ANY($3::text[]) AND province=$4),error_message=$5,updated_at=NOW() WHERE id=$6",[apiCalls,tenantId,brands,record.province,errors.join("；")||null,jobId])}catch(error){apiCalls+=unitCalls;if(error instanceof QuotaPauseError){await query("UPDATE brand_discovery_jobs SET status='额度暂停',control='auto',api_calls=$1,error_message=$2,current_region='',updated_at=NOW() WHERE id=$3",[apiCalls,error.message,jobId]);await scheduleDiscoveryResume(jobId,tenantId,userId);return}errors.push(`${current}：${error instanceof Error?error.message:"查询失败"}`);await query("UPDATE brand_discovery_jobs SET processed_units=processed_units+1,api_calls=$1,error_message=$2,updated_at=NOW() WHERE id=$3",[apiCalls,errors.slice(-20).join("；"),jobId])}}
  const count=Number((await query<Row>("SELECT COUNT(*) count FROM brand_stores WHERE tenant_id=$1 AND brand_name=ANY($2::text[]) AND province=$3",[tenantId,brands,record.province])).rows[0]?.count||0);await query("UPDATE brand_discovery_jobs SET status=$1,control='idle',found_stores=$2,current_region='',completed_at=NOW(),updated_at=NOW() WHERE id=$3",[errors.length?"部分完成":"已完成",count,jobId]);
}

export type BrandStoreFilter={brand?:string;province?:string;city?:string;district?:string;keyword?:string;status?:string;analyzed?:string;page?:number;page_size?:number};
function storeFilterSql(tenantId:number,filter:BrandStoreFilter){const clauses=["bs.tenant_id=$1"],values:any[]=[tenantId];const add=(sql:string,value:unknown)=>{values.push(value);clauses.push(sql.replace("?",`$${values.length}`))};if(filter.brand)add("bs.brand_name=?",filter.brand);if(filter.province)add("bs.province=?",filter.province);if(filter.city)add("bs.city=?",filter.city);if(filter.district)add("bs.district=?",filter.district);if(filter.status&&normalizeStatus(filter.status))add("bs.data_status=?",filter.status);if(filter.keyword){const keyword=`%${filter.keyword}%`;values.push(keyword);const nameIndex=values.length;values.push(keyword);clauses.push(`(bs.amap_name ILIKE $${nameIndex} OR bs.address ILIKE $${values.length})`)}if(filter.analyzed==="yes")clauses.push("EXISTS(SELECT 1 FROM stores s WHERE s.brand_store_id=bs.id AND s.tenant_id=bs.tenant_id AND s.analysis_json IS NOT NULL)");if(filter.analyzed==="no")clauses.push("NOT EXISTS(SELECT 1 FROM stores s WHERE s.brand_store_id=bs.id AND s.tenant_id=bs.tenant_id AND s.analysis_json IS NOT NULL)");return {where:clauses.join(" AND "),values}}
export async function listBrandStores(tenantId:number,filter:BrandStoreFilter){const page=Math.max(1,Number(filter.page||1)),pageSize=Math.max(1,Math.min(200,Number(filter.page_size||50))),built=storeFilterSql(tenantId,filter),total=Number((await query<Row>(`SELECT COUNT(*) count FROM brand_stores bs WHERE ${built.where}`,built.values)).rows[0]?.count||0),values=[...built.values,pageSize,(page-1)*pageSize],rows=(await query<Row>(`SELECT bs.*,EXISTS(SELECT 1 FROM stores s WHERE s.brand_store_id=bs.id AND s.tenant_id=bs.tenant_id AND s.analysis_json IS NOT NULL) analyzed FROM brand_stores bs WHERE ${built.where} ORDER BY bs.city,bs.district,bs.brand_name,bs.amap_name LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;return {rows:rows.map(serializeBrandStore),total,page,page_size:pageSize,pages:Math.ceil(total/pageSize)}}
export async function listBrandStoreIds(tenantId:number,filter:BrandStoreFilter){const built=storeFilterSql(tenantId,filter);return (await query<Row>(`SELECT bs.id FROM brand_stores bs WHERE ${built.where} ORDER BY bs.id LIMIT 5000`,built.values)).rows.map(row=>Number(row.id))}
export async function listDiscoveryJobStoreIds(tenantId:number,job:Row){const brands=uniqueStrings(job.brands_json),cities=uniqueStrings(job.cities_json),province=clean(job.province);if(!brands.length||!province)return [];const values:unknown[]=[tenantId,brands,province];let cityClause="";if(cities.length){values.push(cities);cityClause=` AND city=ANY($${values.length}::text[])`}return (await query<Row>(`SELECT id FROM brand_stores WHERE tenant_id=$1 AND brand_name=ANY($2::text[]) AND province=$3${cityClause} ORDER BY id LIMIT 5000`,values)).rows.map(row=>Number(row.id))}
export async function brandStoreFacets(tenantId:number,province=""){const params:any[]=[tenantId],clause=province?(params.push(province)," AND province=$2"):"";const rows=(await query<Row>(`SELECT brand_name,province,city,district,COUNT(*)::int count FROM brand_stores WHERE tenant_id=$1${clause} GROUP BY brand_name,province,city,district ORDER BY province,city,district,brand_name`,params)).rows;return rows.map(row=>({...row,count:Number(row.count)}))}
export function serializeBrandStore(row:Row){return {id:Number(row.id),brand_name:row.brand_name,amap_poi_id:row.amap_poi_id,amap_name:row.amap_name,province:row.province,city:row.city,district:row.district,address:row.address,location:[Number(row.longitude),Number(row.latitude)],poi_type:row.poi_type,typecode:row.typecode,data_status:row.data_status,analyzed:Boolean(row.analyzed),first_seen_at:row.first_seen_at,last_seen_at:row.last_seen_at,updated_at:row.updated_at}}

export type PoiCondition={category:string;radius:number;operator:"gte"|"lte"|"eq"|"between";value:number;max_value?:number};
export function normalizePoiConditions(value:unknown):PoiCondition[]{const allowed=new Set([...Object.keys(POI_CATEGORY_TYPES),"竞品门店"]),operators=new Set(["gte","lte","eq","between"]),rows=Array.isArray(value)?value.slice(0,20):[];return rows.map(item=>{const row=(item&&typeof item==="object"?item:{}) as Row,category=clean(row.category),radius=Math.round(Number(row.radius)),operator=clean(row.operator),amount=Math.round(Number(row.value)),maximum=Math.round(Number(row.max_value));if(!allowed.has(category)||!Number.isFinite(radius)||radius<50||radius>50000||!operators.has(operator)||!Number.isFinite(amount)||amount<0||amount>10000)throw new Error("POI筛选条件无效，请检查分类、半径、运算符和数量");return {category,radius,operator:operator as PoiCondition["operator"],value:amount,...(operator==="between"?{max_value:Number.isFinite(maximum)&&maximum>=amount?maximum:amount}:{})}})}
function schoolKey(poi:Poi){return clean(poi.name).replace(/[（(](?:东门|西门|南门|北门|停车场|公交站)[）)]/g,"").replace(/(?:东门|西门|南门|北门|停车场|公交站)$/g,"").replace(/\s+/g,"")}
export function effectivePoiCount(pois:Poi[],category:string,radius:number){const inside=pois.filter(poi=>poi.category===category&&Number(poi.distance)<=radius),effective=(category==="小学"||category==="中学")?new Set(inside.map(schoolKey).filter(Boolean)).size:inside.length;return {raw:inside.length,effective}}
export function evaluateConditions(pois:Poi[],conditions:PoiCondition[],relation:"and"|"or"="and"){const details=conditions.map(condition=>{const count=effectivePoiCount(pois,condition.category,condition.radius),value=Number(condition.value||0),max=Number(condition.max_value||value),passed=condition.operator==="lte"?count.effective<=value:condition.operator==="eq"?count.effective===value:condition.operator==="between"?count.effective>=value&&count.effective<=max:count.effective>=value;return {...condition,raw_count:count.raw,effective_count:count.effective,passed}}),passed=details.length?(relation==="or"?details.some(item=>item.passed):details.every(item=>item.passed)):true;return {passed,details}}

export function estimateAnalysis(selected:number,conditions:PoiCondition[]){const categories=[...new Set(conditions.map(item=>item.category))],radii=[...new Set(conditions.map(item=>Number(item.radius)))],maxPages=Math.max(1,Math.min(3,Number(process.env.AMAP_POI_MAX_PAGES||2)));return {stores:selected,categories,radii,estimated_calls:selected*categories.length*maxPages}}

export async function createAnalysisJobFromLibrary(tenantId:number,userId:number,input:Row){const ids=[...new Set((Array.isArray(input.store_ids)?input.store_ids:[]).map(Number).filter(Number.isInteger))],conditions=normalizePoiConditions(input.conditions),relation=input.relation==="or"?"or":"and";if(!ids.length||ids.length>5000)throw new Error("请选择1–5000家品牌门店");if(!conditions.length)throw new Error("请至少设置一个POI筛选条件");const categories=[...new Set(conditions.map(item=>clean(item.category)).filter(Boolean))],radii=[...new Set(conditions.map(item=>Number(item.radius)).filter(item=>item>0))].sort((a,b)=>a-b),config={categories,radii,conditions,condition_relation:relation,brand_library:true},clientRows=(await query<Row>("SELECT * FROM brand_stores WHERE tenant_id=$1 AND id=ANY($2::bigint[])",[tenantId,ids])).rows;if(clientRows.length!==ids.length)throw new Error("部分品牌门店不存在");const client=(await import("./db.js")).pool;const connection=await client.connect();try{await connection.query("BEGIN");const job=(await connection.query<Row>("INSERT INTO jobs(tenant_id,created_by,filename,status,total_stores,matched_stores,config_json,stage,control) VALUES($1,$2,$3,'已进入分析队列',$4,$4,$5,'analysis','run') RETURNING *",[tenantId,userId,`品牌门店POI条件反查_${new Date().toISOString().slice(0,10)}`,ids.length,JSON.stringify(config)])).rows[0];for(const item of clientRows)await connection.query("INSERT INTO stores(tenant_id,created_by,job_id,brand_store_id,input_name,standard_name,amap_poi_id,longitude,latitude,province,city,district,address,brand,match_score,match_status,status) VALUES($1,$2,$3,$4,$5,$5,$6,$7,$8,$9,$10,$11,$12,$13,100,'品牌库门店','已确认')",[tenantId,userId,job.id,item.id,item.amap_name,item.amap_poi_id,item.longitude,item.latitude,item.province,item.city,item.district,item.address,item.brand_name]);await connection.query("COMMIT");return {job_id:Number(job.id),status:"已进入分析队列",estimate:estimateAnalysis(ids.length,conditions)}}catch(error){await connection.query("ROLLBACK");throw error}finally{connection.release()}}

export async function analysisResults(tenantId:number,userId:number,jobId:number){const job=(await query<Row>("SELECT * FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows[0];if(!job)throw new Error("分析任务不存在");const conditions=(job.config_json?.conditions||[]) as PoiCondition[],relation=job.config_json?.condition_relation==="or"?"or":"and",rows=(await query<Row>("SELECT s.*,bs.brand_name,bs.data_status FROM stores s JOIN brand_stores bs ON bs.id=s.brand_store_id WHERE s.job_id=$1 AND s.tenant_id=$2 AND s.created_by=$3 ORDER BY s.id",[jobId,tenantId,userId])).rows;return {job_id:jobId,status:job.status,conditions,relation,rows:rows.map(row=>{const ready=row.status==="分析完成"&&Array.isArray(row.pois_json),evaluation=ready?evaluateConditions(row.pois_json,conditions,relation):null;return {store_id:Number(row.id),brand_store_id:Number(row.brand_store_id),brand_name:row.brand_name,name:row.input_name,province:row.province,city:row.city,district:row.district,address:row.address,status:ready?(evaluation!.passed?"符合":"不符合"):row.status==="分析失败"?"分析失败":"待补全",failure_reason:row.error_message||"",evaluation,pois:ready?row.pois_json:[]}})}}

export async function buildAnalysisResultsWorkbook(tenantId:number,userId:number,jobId:number){const data=await analysisResults(tenantId,userId,jobId),workbook=new ExcelJS.Workbook(),summary=workbook.addWorksheet("筛选结果"),conditionHeaders=data.conditions.flatMap(condition=>[`${condition.radius}米${condition.category}有效数量`,`${condition.radius}米${condition.category}高德原始数量`]),headers=["判定","品牌","门店名称","省份","城市","区县","地址",...conditionHeaders,"失败或待补全原因"];summary.addRow(headers);for(const row of data.rows){const values=(row.evaluation?.details||[]).flatMap((item:Row)=>[item.effective_count,item.raw_count]);summary.addRow([row.status,row.brand_name,row.name,row.province,row.city,row.district,row.address,...values,row.failure_reason])}summary.views=[{state:"frozen",ySplit:1}];summary.autoFilter={from:{row:1,column:1},to:{row:1,column:headers.length}};summary.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};summary.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF08745B"}};summary.columns=headers.map((header,index)=>({width:index===2||index===6?32:18}));const details=workbook.addWorksheet("POI明细");details.addRow(["品牌","门店名称","门店状态","POI分类","POI名称","地址","距离（米）","高德POI ID"]);for(const row of data.rows)for(const poi of row.pois as Poi[])details.addRow([row.brand_name,row.name,row.status,poi.category,poi.name,poi.address,poi.distance,poi.id]);details.views=[{state:"frozen",ySplit:1}];details.autoFilter={from:{row:1,column:1},to:{row:1,column:8}};details.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};details.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF08745B"}};details.columns=[18,32,14,16,30,36,14,20].map(width=>({width}));return Buffer.from(await workbook.xlsx.writeBuffer())}

export const BRAND_EXPORT_FIELDS=[{id:"brand_name",label:"品牌标准名"},{id:"amap_name",label:"高德门店名称"},{id:"province",label:"省份"},{id:"city",label:"城市"},{id:"district",label:"区县"},{id:"address",label:"详细地址"},{id:"longitude",label:"经度"},{id:"latitude",label:"纬度"},{id:"amap_poi_id",label:"高德POI ID"},{id:"poi_type",label:"高德分类"},{id:"data_status",label:"数据状态"},{id:"last_seen_at",label:"查询时间"},{id:"analyzed",label:"是否已做POI分析"}];
export async function buildBrandStoreWorkbook(tenantId:number,ids:number[],fields:string[],filter:BrandStoreFilter={}){const selected=BRAND_EXPORT_FIELDS.filter(field=>fields.includes(field.id));if(!selected.length)throw new Error("请至少选择一个导出字段");const built=ids.length?{where:"bs.tenant_id=$1 AND bs.id=ANY($2::bigint[])",values:[tenantId,ids]}:storeFilterSql(tenantId,filter),rows=(await query<Row>(`SELECT bs.*,EXISTS(SELECT 1 FROM stores s WHERE s.brand_store_id=bs.id AND s.tenant_id=bs.tenant_id AND s.analysis_json IS NOT NULL) analyzed FROM brand_stores bs WHERE ${built.where} ORDER BY bs.province,bs.city,bs.district,bs.brand_name`,built.values)).rows,workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("品牌门店库");sheet.addRow(selected.map(item=>item.label));for(const row of rows){const normalized:Record<string,unknown>={...row,longitude:row.longitude,latitude:row.latitude,analyzed:row.analyzed?"是":"否",last_seen_at:row.last_seen_at?new Date(row.last_seen_at).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):""};sheet.addRow(selected.map(field=>normalized[field.id]??""))}sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF08745B"}};sheet.views=[{state:"frozen",ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:selected.length}};sheet.columns=selected.map(field=>({width:["address","amap_name"].includes(field.id)?32:18}));return Buffer.from(await workbook.xlsx.writeBuffer())}

const BRAND_EXPORT_ROOT=process.env.BRAND_EXPORT_DIR||path.resolve("outputs/brand-exports");
export async function createBrandExport(tenantId:number,userId:number,input:Row){const ids:number[]=[...new Set<number>((Array.isArray(input.store_ids)?input.store_ids:[]).map(Number).filter((value:number)=>Number.isInteger(value)))],fields=uniqueStrings(input.fields),filter=(input.filters&&typeof input.filters==="object"?input.filters:{}) as BrandStoreFilter;if(ids.length>5000)throw new Error("单次勾选导出最多5000家；如需更多，请清空勾选后按当前筛选条件导出");if(!fields.length)throw new Error("请至少选择一个导出字段");const row=(await query<Row>("INSERT INTO brand_export_jobs(tenant_id,created_by,status,request_json) VALUES($1,$2,'pending',$3) RETURNING *",[tenantId,userId,JSON.stringify({store_ids:ids,fields,filters:filter})])).rows[0];return serializeBrandExport(row)}
export async function processBrandExport(exportId:number,tenantId:number,userId:number){const row=(await query<Row>("SELECT * FROM brand_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[exportId,tenantId,userId])).rows[0];if(!row)throw new Error("品牌门店导出任务不存在");await query("UPDATE brand_export_jobs SET status='running',updated_at=NOW() WHERE id=$1",[exportId]);const request=row.request_json||{},buffer=await buildBrandStoreWorkbook(tenantId,(request.store_ids||[]).map(Number),uniqueStrings(request.fields),request.filters||{});await fs.mkdir(BRAND_EXPORT_ROOT,{recursive:true});const filePath=path.join(BRAND_EXPORT_ROOT,`brand-library-${exportId}.xlsx`);await fs.writeFile(filePath,buffer);await query("UPDATE brand_export_jobs SET status='completed',file_path=$1,file_expires_at=NOW()+INTERVAL '30 days',completed_at=NOW(),updated_at=NOW() WHERE id=$2",[filePath,exportId]);return {filePath}}
export function serializeBrandExport(row:Row){return {id:Number(row.id),status:row.status,error_message:row.error_message||"",download_ready:row.status==="completed"&&Boolean(row.file_path)&&(!row.file_expires_at||new Date(row.file_expires_at)>new Date()),file_expires_at:row.file_expires_at||null,created_at:row.created_at,updated_at:row.updated_at,completed_at:row.completed_at||null}}
