import express, { type Request, type Response } from "express";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import compression from "compression";
import multer from "multer";
import bcrypt from "bcryptjs";
import Redis from "ioredis";
import pinoHttp from "pino-http";
import ExcelJS from "exceljs";
import fs from "node:fs/promises";
import crypto from "node:crypto";
import { authenticate, createSession, destroySession, requireAdmin, verifyPassword } from "./auth.js";
import { audit, pool, query } from "./db.js";
import { analyzeImportMapping, parseImportRows } from "./import-reader.js";
import { enqueueAndWait, redisUrl, taskQueue } from "./queue.js";
import { clean, createEnhancedAnalysis as createAnalysis, createSummary, discoverBrandStores, geocode, POI_CATEGORY_TYPES, PROFILE_CATEGORIES, resolveStoreCandidates, searchCandidates, searchPois, type Poi, type Row } from "./services.js";
import { persistentAmapPoiId, prepareStoreResolutionInput } from "./store-resolution.js";
import { buildBatchExportWorkbook, EXPORT_BASE_FIELDS, type ExportSelection } from "./batch-export.js";
import { createAiExport, normalizeAiExportRequest, previewAiExport, serializeAiExport } from "./ai-export.js";
import { normalizeActivityConfig, validateActivityConfig } from "./activity-ai.js";
import { analysisResults, BRAND_EXPORT_FIELDS, brandStoreFacets, buildAnalysisResultsWorkbook, buildBrandStoreWorkbook, cleanupBrandLibraryRetention, createAnalysisJobFromLibrary, createBrandExport, createDiscoveryJob, estimateAnalysis, listBrands, listBrandStoreIds, listBrandStores, listDiscoveryJobStoreIds, listProvinceCities, normalizePoiConditions, PROVINCES, serializeBrandExport, serializeDiscoveryJob, usageSummary } from "./brand-library.js";
import { buildWeComLoginUrl, createWeComState, getWeComAccessToken, getWeComIdentity, getWeComMember, readWeComConfig, safeNextPath, type WeComConfig, type WeComMember } from "./wecom-auth.js";

const app=express(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||15)*1024*1024}}),redis=new Redis(redisUrl,{maxRetriesPerRequest:1});
app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:"2mb"}));app.use(cookieParser());app.use(pinoHttp({redact:["req.headers.authorization","req.headers.cookie","res.headers.set-cookie","req.body.password"]}));

const ok=(res:Response,data:unknown,message="操作成功",status=200)=>res.status(status).json({success:true,data,message});
const fail=(res:Response,message:string,status=400,code="REQUEST_ERROR")=>res.status(status).json({success:false,data:null,message,error:{code,message}});
const ip=(req:Request)=>req.ip||req.socket.remoteAddress||"";

app.use(async(req,res,next)=>{if(req.path==="/api/health")return next();try{const key=`rate:${ip(req)}:${Math.floor(Date.now()/60000)}`,count=await redis.incr(key);if(count===1)await redis.expire(key,70);if(count>Number(process.env.RATE_LIMIT_PER_MINUTE||180))return fail(res,"请求过于频繁，请稍后再试",429,"RATE_LIMIT");next()}catch{next()}});
app.use((req,res,next)=>{if(["GET","HEAD","OPTIONS"].includes(req.method))return next();const expected=process.env.APP_ORIGIN,origin=req.headers.origin;if(expected&&origin&&origin!==expected)return fail(res,"请求来源不受信任",403,"ORIGIN_DENIED");next()});

app.get("/api/health",async(_req,res)=>{try{await query("SELECT 1");await redis.ping();ok(res,{status:"ok",database:"postgresql",queue:"redis",mock:false,web_key:Boolean(process.env.AMAP_WEB_SERVICE_KEY),js_key:Boolean(process.env.NEXT_PUBLIC_AMAP_JS_KEY),coordinate_system:"GCJ-02",runtime:"node"})}catch(error){fail(res,error instanceof Error?error.message:"依赖服务异常",503,"UNHEALTHY")}});
app.post("/api/auth/login",async(req,res)=>{const email=clean(req.body?.email),password=String(req.body?.password||"");const attempts=Number(await redis.get(`login:${ip(req)}:${email.toLowerCase()}`)||0);if(attempts>=10)return fail(res,"登录失败次数过多，请 15 分钟后再试",429);const userId=await verifyPassword(email,password);if(!userId){const key=`login:${ip(req)}:${email.toLowerCase()}`;await redis.multi().incr(key).expire(key,900).exec();return fail(res,"邮箱或密码错误",401)}await createSession(userId,res);await redis.del(`login:${ip(req)}:${email.toLowerCase()}`);const user=(await query<Row>("SELECT id,tenant_id,email,display_name,role FROM users WHERE id=$1",[userId])).rows[0];await audit(Number(user.tenant_id),userId,"login","user",userId,ip(req));ok(res,{id:Number(user.id),email:user.email,display_name:user.display_name,role:user.role})});
app.get("/api/auth/wecom/config",(_req,res)=>ok(res,{enabled:Boolean(readWeComConfig())}));

async function resolveWeComUser(config:WeComConfig,member:WeComMember){
  const existing=(await query<Row>("SELECT id,tenant_id,email,display_name,role FROM users WHERE wecom_corp_id=$1 AND wecom_user_id=$2 ORDER BY id LIMIT 1",[config.corpId,member.userid])).rows[0];
  if(existing){await query("UPDATE users SET display_name=$1,wecom_avatar=$2 WHERE id=$3",[member.name,member.avatar||null,existing.id]);return {...existing,display_name:member.name}}
  let tenantId=config.tenantId;
  if(tenantId){const tenant=(await query<Row>("SELECT id FROM tenants WHERE id=$1",[tenantId])).rows[0];if(!tenant)throw new Error("企业微信绑定的组织不存在")}
  else tenantId=Number((await query<Row>("SELECT id FROM tenants ORDER BY id LIMIT 1")).rows[0]?.id||0);
  if(!tenantId)throw new Error("店界 POI 尚未初始化组织")
  if(member.email){
    const byEmail=(await query<Row>("SELECT id,tenant_id,email,display_name,role,wecom_corp_id,wecom_user_id FROM users WHERE tenant_id=$1 AND lower(email)=lower($2) ORDER BY id LIMIT 1",[tenantId,member.email])).rows[0];
    if(byEmail){
      if(byEmail.wecom_user_id&&String(byEmail.wecom_user_id)!==member.userid)throw new Error("该企业邮箱已绑定其他企业微信成员")
      await query("UPDATE users SET wecom_corp_id=$1,wecom_user_id=$2,wecom_avatar=$3,display_name=$4 WHERE id=$5",[config.corpId,member.userid,member.avatar||null,member.name,byEmail.id]);
      return {...byEmail,display_name:member.name};
    }
  }
  const identityHash=crypto.createHash("sha256").update(`${config.corpId}\0${member.userid}`).digest("hex").slice(0,24);
  const accountEmail=member.email||`wecom-${identityHash}@sso.invalid`;
  const passwordHash=await bcrypt.hash(crypto.randomBytes(48).toString("base64url"),12);
  try{return (await query<Row>("INSERT INTO users(tenant_id,email,display_name,password_hash,role,wecom_corp_id,wecom_user_id,wecom_avatar) VALUES($1,$2,$3,$4,'member',$5,$6,$7) RETURNING id,tenant_id,email,display_name,role",[tenantId,accountEmail,member.name,passwordHash,config.corpId,member.userid,member.avatar||null])).rows[0]}
  catch(error){const raced=(await query<Row>("SELECT id,tenant_id,email,display_name,role FROM users WHERE wecom_corp_id=$1 AND wecom_user_id=$2 ORDER BY id LIMIT 1",[config.corpId,member.userid])).rows[0];if(raced)return raced;throw error}
}

app.get("/api/auth/wecom/start",async(req,res)=>{
  try{
    const config=readWeComConfig();if(!config)return res.redirect(303,"/?wecom_error="+encodeURIComponent("企业微信登录尚未启用"));
    const state=createWeComState(),next=safeNextPath(req.query.next);
    await redis.set(`wecom:state:${state}`,JSON.stringify({next}),"EX",300,"NX");
    const requested=clean(req.query.mode),inWeCom=/wxwork/i.test(String(req.headers["user-agent"]||""));
    const mode=requested==="oauth"||inWeCom?"oauth":"qr";
    res.redirect(302,buildWeComLoginUrl(config,state,mode));
  }catch(error){res.redirect(303,"/?wecom_error="+encodeURIComponent(error instanceof Error?error.message:"企业微信登录失败"))}
});

app.get("/api/auth/wecom/callback",async(req,res)=>{
  try{
    const config=readWeComConfig();if(!config)throw new Error("企业微信登录尚未启用");
    const state=clean(req.query.state),code=clean(req.query.code||req.query.auth_code);if(!state||!code)throw new Error("企业微信未返回有效授权信息");
    const stored=await redis.eval("local v=redis.call('GET',KEYS[1]); if v then redis.call('DEL',KEYS[1]) end; return v",1,`wecom:state:${state}`) as string|null;
    if(!stored)throw new Error("登录请求已过期，请重新扫码");
    const next=safeNextPath((JSON.parse(stored) as {next?:unknown}).next);
    const accessToken=await getWeComAccessToken(config,redis),identity=await getWeComIdentity(accessToken,code),member=await getWeComMember(accessToken,identity.userid);
    const user=await resolveWeComUser(config,member),userId=Number(user.id),tenantId=Number(user.tenant_id);
    await createSession(userId,res);await audit(tenantId,userId,"login_wecom","user",userId,ip(req),{wecom_user_id:member.userid});
    res.redirect(303,next);
  }catch(error){const message=(error instanceof Error?error.message:"企业微信登录失败").slice(0,180);res.redirect(303,"/?wecom_error="+encodeURIComponent(message))}
});
app.post("/api/auth/logout",authenticate,async(req,res)=>{await audit(req.user!.tenantId,req.user!.id,"logout","user",req.user!.id,ip(req));await destroySession(req,res);ok(res,{})});
app.get("/api/auth/me",authenticate,(req,res)=>ok(res,req.user));
app.post("/api/auth/change-password",authenticate,async(req,res)=>{const current=String(req.body.current_password||""),next=String(req.body.new_password||"");if(next.length<12)return fail(res,"新密码至少 12 位");const row=(await query<Row>("SELECT password_hash FROM users WHERE id=$1",[req.user!.id])).rows[0];if(!row||!await bcrypt.compare(current,row.password_hash))return fail(res,"当前密码错误",401);const passwordHash=await bcrypt.hash(next,12);await query("UPDATE users SET password_hash=$1 WHERE id=$2",[passwordHash,req.user!.id]);await query("DELETE FROM sessions WHERE user_id=$1",[req.user!.id]);await audit(req.user!.tenantId,req.user!.id,"change_password","user",req.user!.id,ip(req));res.clearCookie("storemap_session",{path:"/"});ok(res,{},"密码已修改，请重新登录")});

app.use("/api",authenticate);
app.get("/api/admin/users",requireAdmin,async(req,res)=>{const rows=(await query<Row>("SELECT id,email,display_name,role,active,created_at FROM users WHERE tenant_id=$1 ORDER BY id",[req.user!.tenantId])).rows;ok(res,rows)});
app.post("/api/admin/users",requireAdmin,async(req,res)=>{const email=clean(req.body.email).toLowerCase(),displayName=clean(req.body.display_name),password=String(req.body.password||""),role=req.body.role==="admin"?"admin":"member";if(!email||!displayName||password.length<10)return fail(res,"姓名、邮箱必填，密码至少 10 位");const passwordHash=await bcrypt.hash(password,12);try{const row=(await query<Row>("INSERT INTO users(tenant_id,email,display_name,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,email,display_name,role,active,created_at",[req.user!.tenantId,email,displayName,passwordHash,role])).rows[0];await audit(req.user!.tenantId,req.user!.id,"create_user","user",row.id,ip(req),{email,role});ok(res,row,"用户已创建",201)}catch{fail(res,"邮箱已存在",409)}});

app.get("/api/poi-categories",(_req,res)=>ok(res,Object.keys(POI_CATEGORY_TYPES).concat("竞品门店").map((name,index)=>({id:index+1,name,display_name:name}))));
app.get("/api/brand-library/options",async(req,res,next)=>{try{await cleanupBrandLibraryRetention(req.user!.tenantId);ok(res,{brands:await listBrands(req.user!.tenantId,req.user!.id),provinces:PROVINCES,usage:await usageSummary(req.user!.tenantId),export_fields:BRAND_EXPORT_FIELDS})}catch(error){next(error)}});
app.get("/api/brand-library/cities",async(req,res,next)=>{try{const province=clean(req.query.province);if(!PROVINCES.includes(province))return fail(res,"请选择有效省份");ok(res,await listProvinceCities(province))}catch(error){next(error)}});
app.post("/api/brand-library/jobs",async(req,res,next)=>{try{const created=await createDiscoveryJob(req.user!.tenantId,req.user!.id,req.body);await taskQueue.add("discover-brand-stores",{jobId:created.id,tenantId:req.user!.tenantId,userId:req.user!.id},{attempts:1});await audit(req.user!.tenantId,req.user!.id,"create_brand_library_job","brand_discovery_job",created.id,ip(req),{province:created.province,cities:created.cities,brands:created.brands});ok(res,created,"品牌门店查询任务已创建",201)}catch(error){next(error)}});
app.get("/api/brand-library/jobs",async(req,res)=>{const values:unknown[]=[req.user!.tenantId],owner=req.user!.role==="admin"?"":(values.push(req.user!.id)," AND created_by=$2"),rows=(await query<Row>(`SELECT * FROM brand_discovery_jobs WHERE tenant_id=$1${owner} ORDER BY id DESC LIMIT 100`,values)).rows;ok(res,rows.map(serializeDiscoveryJob))});
app.get("/api/brand-library/jobs/:id",async(req,res)=>{const values:unknown[]=[req.params.id,req.user!.tenantId],owner=req.user!.role==="admin"?"":(values.push(req.user!.id)," AND created_by=$3"),row=(await query<Row>(`SELECT * FROM brand_discovery_jobs WHERE id=$1 AND tenant_id=$2${owner}`,values)).rows[0];if(!row)return fail(res,"品牌查询任务不存在",404);ok(res,serializeDiscoveryJob(row))});
app.get("/api/brand-library/jobs/:id/store-ids",async(req,res)=>{const values:unknown[]=[req.params.id,req.user!.tenantId],owner=req.user!.role==="admin"?"":(values.push(req.user!.id)," AND created_by=$3"),row=(await query<Row>(`SELECT * FROM brand_discovery_jobs WHERE id=$1 AND tenant_id=$2${owner}`,values)).rows[0];if(!row)return fail(res,"品牌查询任务不存在",404);ok(res,await listDiscoveryJobStoreIds(req.user!.tenantId,row))});
app.post("/api/brand-library/jobs/:id/pause",async(req,res)=>{const owner=req.user!.role==="admin"?"":" AND created_by=$3",values=req.user!.role==="admin"?[req.params.id,req.user!.tenantId]:[req.params.id,req.user!.tenantId,req.user!.id],result=await query(`UPDATE brand_discovery_jobs SET control='pause',status='已暂停',updated_at=NOW() WHERE id=$1 AND tenant_id=$2${owner} AND status IN ('等待执行','正在读取区域','正在查询','额度暂停')`,values);if(!result.rowCount)return fail(res,"任务不存在或已经结束",404);ok(res,{id:Number(req.params.id)},"任务已暂停")});
app.post("/api/brand-library/jobs/:id/resume",async(req,res)=>{const owner=req.user!.role==="admin"?"":" AND created_by=$3",values=req.user!.role==="admin"?[req.params.id,req.user!.tenantId]:[req.params.id,req.user!.tenantId,req.user!.id],row=(await query<Row>(`UPDATE brand_discovery_jobs SET control='run',status='等待继续',error_message=NULL,updated_at=NOW() WHERE id=$1 AND tenant_id=$2${owner} AND status IN ('已暂停','额度暂停','部分完成') RETURNING *`,values)).rows[0];if(!row)return fail(res,"任务不存在或无法继续",404);await taskQueue.add("discover-brand-stores",{jobId:Number(row.id),tenantId:req.user!.tenantId,userId:Number(row.created_by)},{attempts:1});ok(res,serializeDiscoveryJob(row),"任务已继续")});
app.get("/api/brand-library/stores",async(req,res,next)=>{try{ok(res,await listBrandStores(req.user!.tenantId,{brand:clean(req.query.brand),province:clean(req.query.province),city:clean(req.query.city),district:clean(req.query.district),keyword:clean(req.query.keyword),status:clean(req.query.status),analyzed:clean(req.query.analyzed),page:Number(req.query.page||1),page_size:Number(req.query.page_size||50)}))}catch(error){next(error)}});
app.get("/api/brand-library/store-ids",async(req,res,next)=>{try{ok(res,await listBrandStoreIds(req.user!.tenantId,{brand:clean(req.query.brand),province:clean(req.query.province),city:clean(req.query.city),district:clean(req.query.district),keyword:clean(req.query.keyword),status:clean(req.query.status),analyzed:clean(req.query.analyzed)}))}catch(error){next(error)}});
app.get("/api/brand-library/facets",async(req,res,next)=>{try{ok(res,await brandStoreFacets(req.user!.tenantId,clean(req.query.province)))}catch(error){next(error)}});
app.post("/api/brand-library/export",async(req,res,next)=>{try{const ids:number[]=[...new Set<number>((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number).filter((value:number)=>Number.isInteger(value)))],fields=Array.isArray(req.body.fields)?req.body.fields.map(clean):BRAND_EXPORT_FIELDS.map(item=>item.id);sendXlsx(res,await buildBrandStoreWorkbook(req.user!.tenantId,ids,fields),`品牌门店库_${new Date().toISOString().slice(0,10)}.xlsx`)}catch(error){next(error)}});
app.post("/api/brand-library/exports",async(req,res,next)=>{try{const created=await createBrandExport(req.user!.tenantId,req.user!.id,req.body);await taskQueue.add("brand-library-export",{exportId:created.id,tenantId:req.user!.tenantId,userId:req.user!.id},{attempts:1});ok(res,created,"品牌门店导出任务已创建",201)}catch(error){next(error)}});
app.get("/api/brand-library/exports/:id",async(req,res)=>{const row=(await query<Row>("SELECT * FROM brand_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!row)return fail(res,"导出任务不存在",404);ok(res,serializeBrandExport(row))});
app.get("/api/brand-library/exports/:id/download",async(req,res,next)=>{try{const row=(await query<Row>("SELECT * FROM brand_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!row)return fail(res,"导出任务不存在",404);if(row.status!=="completed"||!row.file_path)return fail(res,"文件尚未生成",409);if(row.file_expires_at&&new Date(row.file_expires_at)<=new Date())return fail(res,"文件已过期，请重新生成",410);sendXlsx(res,await fs.readFile(String(row.file_path)),`品牌门店库_${row.id}.xlsx`)}catch(error){next(error)}});
app.post("/api/brand-library/analysis-preview",async(req,res,next)=>{try{const count=Array.isArray(req.body.store_ids)?new Set(req.body.store_ids.map(Number)).size:0,conditions=normalizePoiConditions(req.body.conditions);if(!count||!conditions.length)return fail(res,"请选择门店并设置POI筛选条件");ok(res,{...estimateAnalysis(count,conditions),usage:await usageSummary(req.user!.tenantId)})}catch(error){next(error)}});
app.post("/api/brand-library/analysis-jobs",async(req,res,next)=>{try{const created=await createAnalysisJobFromLibrary(req.user!.tenantId,req.user!.id,req.body);await taskQueue.add("analyze-batch",{jobId:created.job_id,tenantId:req.user!.tenantId,userId:req.user!.id});await audit(req.user!.tenantId,req.user!.id,"create_brand_library_analysis","job",created.job_id,ip(req),created.estimate);ok(res,created,"POI条件反查任务已创建",201)}catch(error){next(error)}});
app.get("/api/brand-library/analysis-jobs/:id/results",async(req,res,next)=>{try{ok(res,await analysisResults(req.user!.tenantId,req.user!.id,Number(req.params.id)))}catch(error){next(error)}});
app.get("/api/brand-library/analysis-jobs/:id/export",async(req,res,next)=>{try{sendXlsx(res,await buildAnalysisResultsWorkbook(req.user!.tenantId,req.user!.id,Number(req.params.id)),`品牌门店POI条件反查_${req.params.id}.xlsx`)}catch(error){next(error)}});
app.post("/api/admin/brand-library/brands/:id/approve",requireAdmin,async(req,res)=>{const aliases=Array.isArray(req.body.aliases)?req.body.aliases.map(clean).filter(Boolean):[],result=await query("UPDATE brand_catalog SET approval_status='approved',aliases_json=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3",[JSON.stringify(aliases),req.params.id,req.user!.tenantId]);if(!result.rowCount)return fail(res,"品牌不存在",404);ok(res,{id:Number(req.params.id)},"品牌已审核")});
app.post("/api/geocode",async(req,res,next)=>{try{ok(res,{candidates:await geocode(req.body)})}catch(error){next(error)}});
app.post("/api/stores/search",async(req,res,next)=>{try{const name=clean(req.body.name),address=clean(req.body.address);if(!name&&!address)return fail(res,"请至少填写门店名称或详细地址");ok(res,{candidates:await resolveStoreCandidates({...req.body,originalName:name,searchName:name})})}catch(error){next(error)}});
app.post("/api/brand-stores/search",async(req,res,next)=>{try{ok(res,await discoverBrandStores(clean(req.body.brand),clean(req.body.city),clean(req.body.district)),"品牌门店查询完成")}catch(error){next(error)}});
app.post("/api/brand-stores/import",async(req,res)=>{const stores=Array.isArray(req.body.stores)?req.body.stores.slice(0,5000):[],brand=clean(req.body.brand),city=clean(req.body.city),config=req.body.config||{};if(!stores.length)return fail(res,"请至少选择一家品牌门店");const client=await pool.connect();try{await client.query("BEGIN");const filename=`品牌门店查询_${brand||"未命名品牌"}_${city||"未指定城市"}`,job=(await client.query<Row>("INSERT INTO jobs(tenant_id,created_by,filename,status,total_stores,processed_stores,matched_stores,config_json,stage,control) VALUES($1,$2,$3,'匹配完成',$4,$4,$4,$5,'match','idle') RETURNING id",[req.user!.tenantId,req.user!.id,filename,stores.length,config])).rows[0];for(const item of stores){const location=Array.isArray(item.location)?item.location:[null,null];await client.query("INSERT INTO stores(tenant_id,created_by,job_id,input_name,standard_name,amap_poi_id,longitude,latitude,province,city,district,address,brand,match_score,match_status,status) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8,$9,$10,$11,$12,100,'品牌查询命中','已确认')",[req.user!.tenantId,req.user!.id,job.id,clean(item.name),clean(item.id),location[0],location[1],clean(item.province),clean(item.city),clean(item.district),clean(item.address),brand])}await client.query("COMMIT");await audit(req.user!.tenantId,req.user!.id,"create_brand_discovery_job","job",job.id,ip(req),{brand,city,store_count:stores.length});ok(res,{job_id:Number(job.id),status:"匹配完成"},"品牌门店已创建为批量任务",201)}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});
app.post("/api/stores/from-geocode",async(req,res)=>{const candidate=req.body.candidate||{},location=Array.isArray(candidate.location)?candidate.location:[null,null],row=(await query<Row>("INSERT INTO stores(tenant_id,created_by,input_name,standard_name,longitude,latitude,province,city,district,address,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'已确认') RETURNING id",[req.user!.tenantId,req.user!.id,clean(req.body.name)||clean(candidate.name),clean(candidate.name),location[0],location[1],clean(candidate.province),clean(candidate.city),clean(candidate.district),clean(candidate.address)])).rows[0];ok(res,{id:Number(row.id)},"门店已创建",201)});
app.post("/api/stores",async(req,res)=>{const candidate=req.body.candidate||{},location=Array.isArray(candidate.location)?candidate.location:[null,null],inputName=clean(req.body.name)||clean(req.body.address)||clean(candidate.name),poiId=persistentAmapPoiId(candidate),row=(await query<Row>("INSERT INTO stores(tenant_id,created_by,input_name,standard_name,amap_poi_id,longitude,latitude,province,city,district,address,match_score,match_status,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'已确认') RETURNING id",[req.user!.tenantId,req.user!.id,inputName,clean(candidate.name),poiId,location[0],location[1],clean(candidate.province),clean(candidate.city),clean(candidate.district),clean(candidate.address),Number(candidate.score||0),clean(candidate.status)])).rows[0];ok(res,{id:Number(row.id)},"门店已创建",201)});
app.post("/api/stores/:id/confirm",async(req,res)=>{const result=await query("SELECT id FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id]);if(!result.rowCount)return fail(res,"门店不存在",404);ok(res,{id:Number(req.params.id)})});

app.post("/api/stores/:id/poi-search",async(req,res,next)=>{try{const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store||store.longitude==null)return fail(res,"请先确认门店位置");const categories=Array.isArray(req.body.categories)?req.body.categories.map(clean):["住宅小区","幼儿园","小学"],radii=Array.isArray(req.body.radii)?req.body.radii.map(Number):[500],job=(await query<Row>("INSERT INTO jobs(tenant_id,created_by,status,total_stores,matched_stores,config_json,stage,control) VALUES($1,$2,'正在查询POI',1,1,$3,'analysis','run') RETURNING id",[req.user!.tenantId,req.user!.id,{categories,radii}])).rows[0],jobId=Number(job.id);await query("UPDATE stores SET job_id=$1 WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[jobId,store.id,req.user!.tenantId,req.user!.id]);const result=await enqueueAndWait<{pois:Poi[];analysis:Row}>("analyze-single",{tenantId:req.user!.tenantId,userId:req.user!.id,storeId:Number(store.id),categories,radii});await query("UPDATE jobs SET status='已完成',processed_stores=1,success_stores=1,control='idle',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,req.user!.tenantId,req.user!.id]);ok(res,{job_id:jobId,pois:result.pois})}catch(error){next(error)}});
app.post("/api/stores/:id/business-district-analysis",async(req,res,next)=>{try{
  const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);
  const job=store.job_id?(await query<Row>("SELECT config_json FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[store.job_id,req.user!.tenantId,req.user!.id])).rows[0]:null,radii=Array.isArray(req.body.radii)?req.body.radii.map(Number):[500],existing=(store.pois_json||[]) as Poi[],existingCategories=new Set(existing.map(poi=>poi.category)),missing=PROFILE_CATEGORIES.filter(category=>!existingCategories.has(category)),extra=missing.length?await searchPois(store,missing,radii):[],all=new Map<string,Poi>();
  for(const poi of [...existing,...extra]){const key=poi.id||`${poi.name}|${poi.location.join(",")}`;if(!all.has(key))all.set(key,poi)}
  const pois=[...all.values()].sort((a,b)=>a.distance-b.distance),categories=[...new Set([...(Array.isArray(job?.config_json?.categories)?job.config_json.categories.map(String):[]),...PROFILE_CATEGORIES])],analysis=createAnalysis(store,pois,radii,categories);
  await query("UPDATE stores SET pois_json=$1,analysis_json=$2,updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND created_by=$5",[JSON.stringify(pois),JSON.stringify(analysis),store.id,req.user!.tenantId,req.user!.id]);
  if(store.job_id)await query("UPDATE jobs SET config_json=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[{...(job?.config_json||{}),radii,categories},store.job_id,req.user!.tenantId,req.user!.id]);
  ok(res,{...analysis,pois});
}catch(error){next(error)}});
app.post("/api/stores/:id/ai-analysis",async(req,res,next)=>{try{const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);const job=store.job_id?(await query<Row>("SELECT config_json FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[store.job_id,req.user!.tenantId,req.user!.id])).rows[0]:null,radii=Array.isArray(req.body.radii)&&req.body.radii.length?req.body.radii.map(Number):(job?.config_json?.radii||[500]),activityConfig=normalizeActivityConfig(req.body.activity_config||{activity_name:"儿童健康饮品亲子活动分析",objective:"识别妈妈带孩子家庭与儿童健康饮品活动触达场景",activity_time:"待业务确认"}),result=await enqueueAndWait("ai-single",{tenantId:req.user!.tenantId,userId:req.user!.id,storeId:Number(store.id),radii,activityConfig});ok(res,result,"儿童健康饮品亲子活动分析已生成")}catch(error){next(error)}});
app.get("/api/stores/:id/ai-analyses",async(req,res)=>{const rows=(await query<Row>("SELECT * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=$3 ORDER BY id DESC LIMIT 30",[req.user!.tenantId,req.user!.id,req.params.id])).rows;ok(res,rows.map(serializeAi))});

function decodeUploadFilename(value:unknown){const filename=clean(value);if(!/[\u00c0-\u00ff]/.test(filename))return filename;const decoded=Buffer.from(filename,"latin1").toString("utf8");return decoded.includes("\uFFFD")?filename:decoded}
async function readImportRows(file:Express.Multer.File){return parseImportRows(file.buffer,decodeUploadFilename(file.originalname)) as Row[]}
app.get("/api/import/template",async(_req,res,next)=>{try{const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("门店导入模板"),headers=["门店名称","省份","城市","区县","详细地址","门店编号","品牌","备注"];sheet.addRow(headers);sheet.addRow(["示例门店","湖北省","武汉市","洪山区","示例路1号","WH001","零食很忙",""]);sheet.getRow(1).font={bold:true};sheet.columns=headers.map(()=>({width:18}));const buffer=Buffer.from(await workbook.xlsx.writeBuffer());res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",'attachment; filename="store-import-template.xlsx"');res.send(buffer)}catch(error){next(error)}});
app.post("/api/import/preview",upload.single("file"),async(req,res,next)=>{try{if(!req.file)return fail(res,"请选择 Excel 或 CSV 文件");const rows=await readImportRows(req.file),headers=rows.length?Object.keys(rows[0]):[],analysis=analyzeImportMapping(headers,rows),mapping=analysis.mapping,seen=new Set<string>();let duplicates=0;const selectable=rows.slice(0,5000).map((row,index)=>{const prepared=prepareStoreResolutionInput(row,mapping),issues:string[]=[];if(!prepared.hasLocator)issues.push("没有可搜索或定位的信息");const key=`${prepared.originalName}|${prepared.address}|${prepared.poiId}|${prepared.longitude},${prepared.latitude}`.toLowerCase();if(key&&seen.has(key)){issues.push("重复门店");duplicates++}if(key)seen.add(key);return {...row,_row_number:index+2,_valid:issues.length===0,_issues:issues,_search_preview:{name:prepared.searchName,address:prepared.address,brand:prepared.brand,locator:prepared.poiId?"高德POI ID":prepared.longitude!=null&&prepared.latitude!=null?"经纬度":prepared.searchName?"门店名称和地址":"详细地址"}}});const warnings=[...(rows.length>5000?["仅处理前 5000 行"]:[]),...analysis.conflicts];ok(res,{filename:decodeUploadFilename(req.file.originalname),file_size:req.file.size,headers,mapping,mapping_analysis:analysis.detections,rows:selectable.slice(0,100),all_rows:rows,selectable_rows:selectable,total_rows:rows.length,valid_rows:selectable.filter(row=>row._valid).length,invalid_rows:selectable.filter(row=>!row._valid).length,duplicate_rows:duplicates,warnings},"文件解析成功")}catch(error){next(error)}});
app.post("/api/import/confirm",async(req,res)=>{const rows=Array.isArray(req.body.rows)?req.body.rows:[],mapping=req.body.mapping||{},config=req.body.config||{};if(!rows.length)return fail(res,"请至少选择一家门店");const preparedRows=rows.map((row:Row)=>prepareStoreResolutionInput(row,mapping)).filter((item:ReturnType<typeof prepareStoreResolutionInput>)=>item.hasLocator);if(!preparedRows.length)return fail(res,"所选行没有可搜索或定位的信息");const client=await pool.connect();try{await client.query("BEGIN");const job=(await client.query<Row>("INSERT INTO jobs(tenant_id,created_by,filename,status,total_stores,config_json,stage,control) VALUES($1,$2,$3,'等待开始匹配',$4,$5,'match','idle') RETURNING id",[req.user!.tenantId,req.user!.id,clean(req.body.filename),preparedRows.length,{...config,import_mapping:mapping}])).rows[0];for(const item of preparedRows)await client.query("INSERT INTO stores(tenant_id,created_by,job_id,input_name,province,city,district,address,user_code,brand,amap_poi_id,longitude,latitude,status,original_row_json,search_input_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'等待匹配',$14,$15)",[req.user!.tenantId,req.user!.id,job.id,item.originalName,item.province,item.city,item.district,item.address,clean(item.originalRow[mapping.code]),item.brand,item.poiId||null,item.longitude,item.latitude,item.originalRow,item]);await client.query("COMMIT");ok(res,{job_id:Number(job.id),status:"等待开始匹配"},"批量任务创建成功",201)}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});

app.get("/api/analysis-jobs",async(req,res)=>{const rows=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 ORDER BY id DESC LIMIT 100",[req.user!.tenantId,req.user!.id])).rows;ok(res,rows.map(serializeJob))});
app.get("/api/analysis-jobs/:id",async(req,res)=>{const row=await ownedJob(req);if(row)ok(res,serializeJob(row));else fail(res,"任务不存在",404)});
app.get("/api/analysis-jobs/:id/stores",async(req,res)=>{if(!await ownedJob(req))return fail(res,"任务不存在",404);const rows=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 ORDER BY id",[req.params.id,req.user!.tenantId,req.user!.id])).rows;ok(res,rows.map(row=>({store:serializeStore(row),status:row.status,poi_summary:createSummary((row.pois_json||[]) as Poi[]),has_profile:Boolean(row.analysis_json),error_message:row.error_message||""})))});
app.post("/api/analysis-jobs/:id/stores/:storeId/confirm-match",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND job_id=$2 AND tenant_id=$3 AND created_by=$4",[req.params.storeId,job.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);const candidates=Array.isArray(store.match_candidates_json)?store.match_candidates_json:[],candidate=req.body.candidate||candidates[Number(req.body.candidate_index||0)];if(!candidate||!Array.isArray(candidate.location))return fail(res,"请选择有效候选");await query("UPDATE stores SET standard_name=$1,amap_poi_id=$2,longitude=$3,latitude=$4,province=$5,city=$6,district=$7,address=$8,match_score=$9,match_status=$10,status='已确认',error_message=NULL,confirmation_method='用户人工确认',updated_at=NOW() WHERE id=$11 AND job_id=$12 AND tenant_id=$13 AND created_by=$14",[clean(candidate.name),clean(candidate.id),Number(candidate.location[0]),Number(candidate.location[1]),clean(candidate.province)||store.province,clean(candidate.city)||store.city,clean(candidate.district)||store.district,clean(candidate.address)||store.address,Number(candidate.score||0),clean(candidate.status)||"用户确认",store.id,job.id,req.user!.tenantId,req.user!.id]);await refreshMatchJobSummary(Number(job.id),req.user!.tenantId,req.user!.id);ok(res,{store_id:Number(store.id)},"门店匹配已确认")});
app.post("/api/analysis-jobs/:id/matches/confirm-best",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const requested=new Set((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number)),rows=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND status='待确认' ORDER BY id",[job.id,req.user!.tenantId,req.user!.id])).rows,targets=requested.size?rows.filter(row=>requested.has(Number(row.id))):rows;let confirmed=0;for(const store of targets){const candidate=Array.isArray(store.match_candidates_json)?store.match_candidates_json[0]:null;if(!candidate||!Array.isArray(candidate.location))continue;await query("UPDATE stores SET standard_name=$1,amap_poi_id=$2,longitude=$3,latitude=$4,province=$5,city=$6,district=$7,address=$8,match_score=$9,match_status=$10,status='已确认',error_message=NULL,confirmation_method='用户批量接受最佳候选',updated_at=NOW() WHERE id=$11 AND tenant_id=$12 AND created_by=$13",[clean(candidate.name),clean(candidate.id),Number(candidate.location[0]),Number(candidate.location[1]),clean(candidate.province)||store.province,clean(candidate.city)||store.city,clean(candidate.district)||store.district,clean(candidate.address)||store.address,Number(candidate.score||0),clean(candidate.status)||"用户确认",store.id,req.user!.tenantId,req.user!.id]);confirmed++}await refreshMatchJobSummary(Number(job.id),req.user!.tenantId,req.user!.id);ok(res,{confirmed},`已确认 ${confirmed} 家门店`)});
app.post("/api/analysis-jobs/:id/stores/:storeId/research",async(req,res,next)=>{try{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND job_id=$2 AND tenant_id=$3 AND created_by=$4",[req.params.storeId,job.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);const candidates=await resolveStoreCandidates({...store.search_input_json,originalName:store.input_name,searchName:clean(req.body.name)||store.input_name,address:clean(req.body.address)||store.address,city:clean(req.body.city)||store.city,district:clean(req.body.district)||store.district,poiId:"",longitude:null,latitude:null});await query("UPDATE stores SET match_candidates_json=$1,match_score=$2,match_status=$3,status=$4,error_message=$5,updated_at=NOW() WHERE id=$6 AND tenant_id=$7 AND created_by=$8",[candidates,Number(candidates[0]?.score||0),clean(candidates[0]?.status),candidates.length?"待确认":"匹配失败",candidates.length?"重新搜索完成，请选择候选":"高德未返回有效候选",store.id,req.user!.tenantId,req.user!.id]);await refreshMatchJobSummary(Number(job.id),req.user!.tenantId,req.user!.id);ok(res,{candidates},candidates.length?"已更新候选":"仍未找到候选")}catch(error){next(error)}});
app.post("/api/analysis-jobs/:id/stores/:storeId/skip-match",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const result=await query("UPDATE stores SET status='已跳过',error_message='用户暂时跳过门店匹配',confirmation_method='用户跳过',updated_at=NOW() WHERE id=$1 AND job_id=$2 AND tenant_id=$3 AND created_by=$4",[req.params.storeId,job.id,req.user!.tenantId,req.user!.id]);if(!result.rowCount)return fail(res,"门店不存在",404);await refreshMatchJobSummary(Number(job.id),req.user!.tenantId,req.user!.id);ok(res,{store_id:Number(req.params.storeId)},"已跳过该门店")});
app.get("/api/analysis-jobs/:id/stores/:storeId",async(req,res)=>{const job=await ownedJob(req),store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND job_id=$2 AND tenant_id=$3 AND created_by=$4",[req.params.storeId,req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!job||!store)return fail(res,"门店不存在",404);const pois=(store.pois_json||[]) as Poi[];ok(res,{job:serializeJob(job),store:serializeStore(store),status:store.status,pois,poi_summary:createSummary(pois),analysis:store.analysis_json||null,disclaimer:"本分析仅反映高德POI设施分布及其代理推断。"})});
app.get("/api/analysis-jobs/:id/business-district-results",async(req,res)=>{
  if(!await ownedJob(req))return fail(res,"任务不存在",404);
  const rows=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND analysis_json IS NOT NULL ORDER BY id",[req.params.id,req.user!.tenantId,req.user!.id])).rows;
  const data=rows.map(row=>({...(row.analysis_json||{}),store:serializeStore(row),poi_summary:createSummary((row.pois_json||[]) as Poi[])}));
  ok(res,data);
});
app.post("/api/analysis-jobs/:id/start-matching",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE jobs SET status='已进入匹配队列',control='run',stage='match',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add("match-batch",{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,status:"已进入匹配队列",control:"run",stage:"match"}),"已进入连续匹配队列")});
app.post("/api/analysis-jobs/:id/start-analysis",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE jobs SET status='已进入分析队列',control='run',stage='analysis',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add("analyze-batch",{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,status:"已进入分析队列",control:"run",stage:"analysis"}),"已进入连续分析队列")});
app.post("/api/analysis-jobs/:id/reanalyze",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const config={...(job.config_json||{}),generate_profile:true,categories:[...new Set([...(Array.isArray(job.config_json?.categories)?job.config_json.categories.map(String):[]),...PROFILE_CATEGORIES])]};await query("UPDATE jobs SET status='已进入分析队列',control='run',stage='analysis',config_json=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[config,job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add("analyze-batch",{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,status:"已进入分析队列",control:"run",stage:"analysis",config_json:config}),"历史任务已进入新规则重算队列")});
app.post("/api/analysis-jobs/:id/:action",async(req,res,next)=>{if(!["pause","end"].includes(req.params.action))return next();const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const pause=req.params.action==="pause";await query("UPDATE jobs SET status=$1,control=$2,updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND created_by=$5",[pause?"已暂停":"已结束",pause?"pause":"end",job.id,req.user!.tenantId,req.user!.id]);ok(res,serializeJob({...job,status:pause?"已暂停":"已结束",control:pause?"pause":"end"}))});
app.post("/api/analysis-jobs/:id/resume",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const name=job.stage==="analysis"?"analyze-batch":"match-batch";await query("UPDATE jobs SET control='run',status=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[job.stage==="analysis"?"已进入分析队列":"已进入匹配队列",job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add(name,{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,control:"run"}),"任务已继续")});
app.post("/api/analysis-jobs/:id/retry",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE stores SET status=CASE WHEN longitude IS NULL THEN '等待匹配' ELSE '已确认' END,error_message=NULL WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND status IN ('匹配失败','分析失败')",[job.id,req.user!.tenantId,req.user!.id]);await query("UPDATE jobs SET status='等待继续匹配',control='idle',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);ok(res,serializeJob({...job,status:"等待继续匹配",control:"idle"}))});
app.post("/api/analysis-jobs/:id/ai-comparison",async(req,res,next)=>{try{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const storeIds=[...new Set((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number))];if(storeIds.length<2||storeIds.length>10)return fail(res,"请选择 2–10 家门店进行 AI 对比");const count=await query("SELECT id FROM stores WHERE tenant_id=$1 AND created_by=$2 AND job_id=$3 AND id=ANY($4::bigint[])",[req.user!.tenantId,req.user!.id,job.id,storeIds]);if(count.rowCount!==storeIds.length)return fail(res,"部分门店不存在或无权访问",403);const result=await enqueueAndWait<Record<string,unknown>>("ai-comparison",{tenantId:req.user!.tenantId,userId:req.user!.id,jobId:Number(job.id),storeIds,radii:job.config_json?.radii||[500]});ok(res,{...result,store_labels:storeIds.map((storeId,index)=>({store_id:storeId,label:`门店${String.fromCharCode(65+index)}`}))},"多店 AI 对比已生成")}catch(error){next(error)}});
app.get("/api/analysis-jobs/:id/ai-comparisons",async(req,res)=>{if(!await ownedJob(req))return fail(res,"任务不存在",404);const rows=(await query<Row>("SELECT * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='comparison' AND job_id=$3 ORDER BY id DESC LIMIT 30",[req.user!.tenantId,req.user!.id,req.params.id])).rows;ok(res,rows.map(serializeAi))});
app.get("/api/batch-export/options",async(req,res)=>{const jobs=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 ORDER BY id DESC LIMIT 100",[req.user!.tenantId,req.user!.id])).rows;ok(res,{jobs:jobs.map(serializeJob),fields:EXPORT_BASE_FIELDS,required_fields:[{id:"store_name",label:"门店名称"},{id:"store_address",label:"门店地址"}],sheet_options:[{id:"poi_details",label:"POI 明细"},{id:"failures",label:"失败与未完成门店"},{id:"notes",label:"导出说明"}]})});
app.get("/api/ai-exports/activity-template",async(_req,res)=>{const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("活动差异配置");sheet.addRow(["门店编号","门店名称","门店地址","活动名称","活动目标","活动时间","单店预算","赠品或资源","允许活动形式","备注"]);sheet.addRow(["可选，优先匹配","与导入表一致","与导入表一致","亲子互动日","触达妈妈带孩子家庭","2026-09-15 14:00-17:00","可选","可选","可选","可选"]);const buffer=Buffer.from(await workbook.xlsx.writeBuffer());sendXlsx(res,buffer,"亲子活动差异配置模板.xlsx")});
app.post("/api/ai-exports/activity-preview",upload.single("file"),async(req,res,next)=>{try{if(!req.file)return fail(res,"请选择活动配置表格");const storeIds=[...new Set((JSON.parse(String(req.body.store_ids||"[]")) as unknown[]).map(Number).filter(Number.isInteger))],stores=(await query<Row>("SELECT id,input_name,address,user_code FROM stores WHERE tenant_id=$1 AND created_by=$2 AND id=ANY($3::bigint[])",[req.user!.tenantId,req.user!.id,storeIds])).rows;if(stores.length!==storeIds.length)return fail(res,"部分门店不存在或无权访问",403);const imported=await readImportRows(req.file),overrides:Record<string,unknown>={},matches:unknown[]=[],errors:string[]=[],seen=new Set<number>();for(let index=0;index<imported.length;index++){const row=imported[index],code=clean(row["门店编号"]),name=clean(row["门店名称"]),address=clean(row["门店地址"]),candidates=code?stores.filter(store=>clean(store.user_code)===code):stores.filter(store=>clean(store.input_name)===name&&(!address||clean(store.address)===address));if(candidates.length!==1){errors.push(`第 ${index+2} 行：${candidates.length?"匹配到多个门店":"未匹配到所选门店"}`);continue}const store=candidates[0],id=Number(store.id);if(seen.has(id)){errors.push(`第 ${index+2} 行：门店重复配置`);continue}seen.add(id);const config=normalizeActivityConfig({activity_name:row["活动名称"],objective:row["活动目标"],activity_time:row["活动时间"],budget:row["单店预算"],gifts:row["赠品或资源"],allowed_formats:row["允许活动形式"],notes:row["备注"]}),validated=validateActivityConfig(config);if(validated.errors.length){errors.push(`第 ${index+2} 行：${validated.errors.join("、")}`);continue}overrides[String(id)]=config;matches.push({row:index+2,store_id:id,store_name:store.input_name})}ok(res,{overrides,matches,errors,valid:errors.length===0,total_rows:imported.length})}catch(error){next(error)}});
app.post("/api/ai-exports/preview",async(req,res,next)=>{try{const request=normalizeAiExportRequest({...req.body,user_email:req.user!.email,job_names:[]});ok(res,await previewAiExport(req.user!.tenantId,req.user!.id,request))}catch(error){next(error)}});
app.post("/api/ai-exports",async(req,res,next)=>{try{const request=normalizeAiExportRequest({...req.body,user_email:req.user!.email,job_names:Array.isArray(req.body.job_names)?req.body.job_names:[]}),created=await createAiExport(req.user!.tenantId,req.user!.id,request);await taskQueue.add("ai-export-batch",{exportId:created.id,tenantId:req.user!.tenantId,userId:req.user!.id},{attempts:1});await audit(req.user!.tenantId,req.user!.id,"create_ai_export","ai_export",created.id,ip(req),{store_count:created.selected,new_generation:created.new_generation});ok(res,created,"AI批量导出任务已创建",201)}catch(error){next(error)}});
app.get("/api/ai-exports",async(req,res)=>{const rows=(await query<Row>("SELECT * FROM ai_export_jobs WHERE tenant_id=$1 AND created_by=$2 AND record_expires_at>NOW() ORDER BY id DESC LIMIT 50",[req.user!.tenantId,req.user!.id])).rows;ok(res,rows.map(serializeAiExport))});
app.get("/api/ai-exports/:id",async(req,res)=>{const row=(await query<Row>("SELECT * FROM ai_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!row)return fail(res,"AI导出任务不存在",404);ok(res,serializeAiExport(row))});
app.post("/api/ai-exports/:id/cancel",async(req,res)=>{const result=await query("UPDATE ai_export_jobs SET control='cancel',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3 AND status IN ('pending','running')",[req.params.id,req.user!.tenantId,req.user!.id]);if(!result.rowCount)return fail(res,"任务不存在或已结束",404);ok(res,{id:Number(req.params.id)},"已请求取消，当前正在生成的门店会完成后停止")});
app.post("/api/ai-exports/:id/retry",async(req,res)=>{const row=(await query<Row>("SELECT * FROM ai_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!row)return fail(res,"AI导出任务不存在",404);await query("UPDATE ai_export_job_stores SET status='pending',error_message=NULL WHERE export_job_id=$1 AND status='failed'",[row.id]);await query("UPDATE ai_export_jobs SET status='pending',control='run',error_message=NULL,file_path=NULL,file_expires_at=NULL,updated_at=NOW() WHERE id=$1",[row.id]);await taskQueue.add("ai-export-batch",{exportId:Number(row.id),tenantId:req.user!.tenantId,userId:req.user!.id},{attempts:1});ok(res,{id:Number(row.id)},"失败门店已重新进入队列")});
app.get("/api/ai-exports/:id/download",async(req,res,next)=>{try{const row=(await query<Row>("SELECT * FROM ai_export_jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!row)return fail(res,"AI导出任务不存在",404);if(row.status!=="completed"||!row.file_path)return fail(res,"文件尚未生成",409);if(row.file_expires_at&&new Date(row.file_expires_at)<=new Date())return fail(res,"文件已过期，请重新生成导出",410);sendXlsx(res,await fs.readFile(String(row.file_path)),`亲子活动AI批量导出_${row.id}.xlsx`)}catch(error){next(error)}});
app.post("/api/batch-export",async(req,res,next)=>{try{
  const jobIds:number[]=[...new Set<number>((Array.isArray(req.body.job_ids)?req.body.job_ids:[]).map(Number).filter(Number.isInteger))];
  if(!jobIds.length||jobIds.length>100)return fail(res,"请选择 1–100 个分析任务");
  const jobs=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 AND id=ANY($3::bigint[]) ORDER BY id",[req.user!.tenantId,req.user!.id,jobIds])).rows;
  if(jobs.length!==jobIds.length)return fail(res,"部分任务不存在或无权访问",403);
  const availableRadii:number[]=[...new Set<number>(jobs.flatMap(job=>Array.isArray(job.config_json?.radii)?job.config_json.radii.map(Number):[]))].sort((a,b)=>a-b);
  const availableCategories:string[]=[...new Set<string>(jobs.flatMap(job=>Array.isArray(job.config_json?.categories)?job.config_json.categories.map(String):[]))];
  const radii:number[]=[...new Set<number>((Array.isArray(req.body.radii)?req.body.radii:availableRadii).map(Number))].filter(radius=>availableRadii.includes(radius));
  const categories:string[]=[...new Set<string>((Array.isArray(req.body.categories)?req.body.categories:availableCategories).map(clean))].filter(category=>availableCategories.includes(category));
  if(!radii.length||!categories.length)return fail(res,"所选任务没有可导出的分析半径或 POI 分类");
  const knownFields=new Set<string>(EXPORT_BASE_FIELDS.map(field=>field.id)),fields:string[]=[...new Set<string>((Array.isArray(req.body.fields)?req.body.fields:[]).map(clean))].filter(field=>knownFields.has(field));
  const storeIds:number[]=[...new Set<number>((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number).filter(Number.isInteger))],params:unknown[]=[req.user!.tenantId,req.user!.id,jobIds],storeClause=storeIds.length?" AND s.id=ANY($4::bigint[])":"",storeParams=storeIds.length?[...params,storeIds]:params;
  const rows=(await query<Row>(`SELECT s.*,j.config_json AS job_config,j.filename AS job_filename FROM stores s JOIN jobs j ON j.id=s.job_id WHERE s.tenant_id=$1 AND s.created_by=$2 AND j.created_by=$2 AND s.job_id=ANY($3::bigint[])${storeClause} ORDER BY s.job_id,s.id`,storeParams)).rows;
  if(storeIds.length&&rows.length!==storeIds.length)return fail(res,"部分门店不存在或无权访问",403);if(!rows.length)return fail(res,"所选任务没有可导出的门店");if(rows.length>5000)return fail(res,"单次最多导出 5,000 家门店");
  const aiRows=(await query<Row>("SELECT DISTINCT ON (store_id) * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=ANY($3::bigint[]) ORDER BY store_id,created_at DESC",[req.user!.tenantId,req.user!.id,rows.map(row=>Number(row.id))])).rows;
  const selection:ExportSelection={jobIds,storeIds,fields,radii,categories,includePoiDetails:Boolean(req.body.include_poi_details),includeFailures:req.body.include_failures!==false,includeNotes:req.body.include_notes!==false},filename=`门店POI批量导出_${new Date().toISOString().slice(0,10)}.xlsx`,buffer=await buildBatchExportWorkbook(rows,aiRows,selection,{userEmail:req.user!.email,jobNames:jobs.map(job=>decodeUploadFilename(job.filename)||`任务#${job.id}`)});
  await audit(req.user!.tenantId,req.user!.id,"batch_export","jobs",jobIds.join(","),ip(req),{store_count:rows.length,radii,categories,fields});sendXlsx(res,buffer,filename);
}catch(error){next(error)}});
app.get(["/api/analysis-jobs/:id/export","/api/analysis-jobs/:id/business-district-export","/api/analysis-jobs/:id/stores/:storeId/export"],exportJob);

async function ownedJob(req:Request){return (await query<Row>("SELECT * FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0]}
async function refreshMatchJobSummary(jobId:number,tenantId:number,userId:number){const rows=(await query<{status:string}>("SELECT status FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows,total=rows.length,matched=rows.filter(row=>["已确认","分析完成","分析失败"].includes(row.status)).length,failed=rows.filter(row=>row.status==="匹配失败").length,review=rows.filter(row=>row.status==="待确认").length,processed=rows.filter(row=>row.status!=="等待匹配").length,status=failed?"匹配部分失败":"匹配完成";await query("UPDATE jobs SET processed_stores=$1,matched_stores=$2,failed_stores=$3,status=$4,control='idle',updated_at=NOW() WHERE id=$5 AND tenant_id=$6 AND created_by=$7",[processed,matched,failed,status,jobId,tenantId,userId]);return {total,matched,failed,review,processed,status}}
function serializeJob(row:Row){const total=Number(row.total_stores||0),stage=row.stage||"match",processed=Number(row.processed_stores||0),stageTotal=stage==="analysis"?Number(row.matched_stores||total):total;return {id:Number(row.id),filename:decodeUploadFilename(row.filename),status:row.status,total_stores:total,processed_stores:processed,matched_stores:Number(row.matched_stores||0),pending_stores:Math.max(0,total-processed),success_stores:Number(row.success_stores||0),failed_stores:Number(row.failed_stores||0),config:row.config_json||{},stage,control:row.control||"idle",stage_total:stageTotal,stage_processed:processed,progress_percent:Math.round(processed/Math.max(1,stageTotal)*100),current_store:row.current_store||"",created_at:new Date(row.created_at).toISOString(),updated_at:new Date(row.updated_at).toISOString()}}
function serializeStore(row:Row){return {id:Number(row.id),input_name:row.input_name,standard_name:row.standard_name,amap_poi_id:row.amap_poi_id,longitude:row.longitude==null?null:Number(row.longitude),latitude:row.latitude==null?null:Number(row.latitude),province:row.province||"",city:row.city||"",district:row.district||"",address:row.address||"",match_score:row.match_score==null?null:Number(row.match_score),match_status:row.match_status||"",match_candidates:Array.isArray(row.match_candidates_json)?row.match_candidates_json:[],confirmation_method:row.confirmation_method||"",location_source:row.amap_poi_id?"高德POI":row.longitude!=null?"用户坐标":"待定位"}}
function serializeAi(row:Row){return {id:Number(row.id),scope:row.scope,job_id:row.job_id==null?null:Number(row.job_id),store_id:row.store_id==null?null:Number(row.store_id),store_ids:row.store_ids_json||[],result:row.result_json||{},model:row.model,prompt_version:row.prompt_version,usage:{input_tokens:Number(row.input_tokens||0),output_tokens:Number(row.output_tokens||0),total_tokens:Number(row.total_tokens||0)},created_at:new Date(row.created_at).toISOString()}}
function sendXlsx(res:Response,buffer:Buffer,filename:string){res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",`attachment; filename="store-poi-export.xlsx"; filename*=UTF-8''${encodeURIComponent(filename)}`);res.setHeader("Access-Control-Expose-Headers","Content-Disposition");res.send(buffer)}
async function exportJob(req:Request,res:Response){const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const params:unknown[]=[req.user!.tenantId,req.user!.id,req.params.id],storeClause=req.params.storeId?" AND s.id=$4":"",rows=(await query<Row>(`SELECT s.*,j.config_json AS job_config,j.filename AS job_filename FROM stores s JOIN jobs j ON j.id=s.job_id WHERE s.tenant_id=$1 AND s.created_by=$2 AND j.created_by=$2 AND s.job_id=$3${storeClause} ORDER BY s.id`,req.params.storeId?[...params,req.params.storeId]:params)).rows;if(!rows.length)return fail(res,"没有可导出的门店",404);const aiRows=(await query<Row>("SELECT DISTINCT ON (store_id) * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=ANY($3::bigint[]) ORDER BY store_id,created_at DESC",[req.user!.tenantId,req.user!.id,rows.map(row=>Number(row.id))])).rows,config=job.config_json||{},selection:ExportSelection={jobIds:[Number(job.id)],storeIds:req.params.storeId?[Number(req.params.storeId)]:[],fields:["city","district","longitude","latitude","status","match_score","poi_total","business_district_type","main_audience","age_ranges","residential_activity_level","residential_activity_index","consumption_level","consumption_index","competitor_total","competitor_same_brand","competitor_other_brand","nearest_competitor","nearest_competitor_distance","competition_level","competition_by_radius","analysis_confidence","ai_summary","ai_confidence","error_message"],radii:Array.isArray(config.radii)?config.radii.map(Number):[500],categories:Array.isArray(config.categories)?config.categories.map(String):[],includePoiDetails:true,includeFailures:true,includeNotes:true},buffer=await buildBatchExportWorkbook(rows,aiRows,selection,{userEmail:req.user!.email,jobNames:[decodeUploadFilename(job.filename)||`任务#${job.id}`]});sendXlsx(res,buffer,req.params.storeId?`门店报告_${rows[0].input_name}.xlsx`:`任务${job.id}_门店POI报告.xlsx`)}

app.use((error:unknown,req:Request,res:Response,next:unknown)=>{void next;req.log.error(error);fail(res,error instanceof Error?error.message:"服务器错误",500,"SERVER_ERROR")});
const port=Number(process.env.API_PORT||8000),server=app.listen(port,"0.0.0.0",()=>console.log(`Node API listening on ${port}`));
async function stop(){server.close();await Promise.allSettled([redis.quit(),taskQueue.close(),pool.end()]);process.exit(0)}process.on("SIGTERM",stop);process.on("SIGINT",stop);
