import express, { type Request, type Response } from "express";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import compression from "compression";
import multer from "multer";
import bcrypt from "bcryptjs";
import Redis from "ioredis";
import pinoHttp from "pino-http";
import ExcelJS from "exceljs";
import { authenticate, createSession, destroySession, requireAdmin, verifyPassword } from "./auth.js";
import { audit, pool, query } from "./db.js";
import { parseImportRows } from "./import-reader.js";
import { enqueueAndWait, redisUrl, taskQueue } from "./queue.js";
import { clean, createEnhancedAnalysis as createAnalysis, createSummary, geocode, POI_CATEGORY_TYPES, searchCandidates, type Poi, type Row } from "./services.js";
import { buildBatchExportWorkbook, EXPORT_BASE_FIELDS, type ExportSelection } from "./batch-export.js";

const app=express(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||15)*1024*1024}}),redis=new Redis(redisUrl,{maxRetriesPerRequest:1});
app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:"2mb"}));app.use(cookieParser());app.use(pinoHttp({redact:["req.headers.authorization","req.headers.cookie","res.headers.set-cookie","req.body.password"]}));

const ok=(res:Response,data:unknown,message="操作成功",status=200)=>res.status(status).json({success:true,data,message});
const fail=(res:Response,message:string,status=400,code="REQUEST_ERROR")=>res.status(status).json({success:false,data:null,message,error:{code,message}});
const ip=(req:Request)=>req.ip||req.socket.remoteAddress||"";

app.use(async(req,res,next)=>{if(req.path==="/api/health")return next();try{const key=`rate:${ip(req)}:${Math.floor(Date.now()/60000)}`,count=await redis.incr(key);if(count===1)await redis.expire(key,70);if(count>Number(process.env.RATE_LIMIT_PER_MINUTE||180))return fail(res,"请求过于频繁，请稍后再试",429,"RATE_LIMIT");next()}catch{next()}});
app.use((req,res,next)=>{if(["GET","HEAD","OPTIONS"].includes(req.method))return next();const expected=process.env.APP_ORIGIN,origin=req.headers.origin;if(expected&&origin&&origin!==expected)return fail(res,"请求来源不受信任",403,"ORIGIN_DENIED");next()});

app.get("/api/health",async(_req,res)=>{try{await query("SELECT 1");await redis.ping();ok(res,{status:"ok",database:"postgresql",queue:"redis",mock:false,web_key:Boolean(process.env.AMAP_WEB_SERVICE_KEY),js_key:Boolean(process.env.NEXT_PUBLIC_AMAP_JS_KEY),coordinate_system:"GCJ-02",runtime:"node"})}catch(error){fail(res,error instanceof Error?error.message:"依赖服务异常",503,"UNHEALTHY")}});
app.post("/api/auth/login",async(req,res)=>{const email=clean(req.body?.email),password=String(req.body?.password||"");const attempts=Number(await redis.get(`login:${ip(req)}:${email.toLowerCase()}`)||0);if(attempts>=10)return fail(res,"登录失败次数过多，请 15 分钟后再试",429);const userId=await verifyPassword(email,password);if(!userId){const key=`login:${ip(req)}:${email.toLowerCase()}`;await redis.multi().incr(key).expire(key,900).exec();return fail(res,"邮箱或密码错误",401)}await createSession(userId,res);await redis.del(`login:${ip(req)}:${email.toLowerCase()}`);const user=(await query<Row>("SELECT id,tenant_id,email,display_name,role FROM users WHERE id=$1",[userId])).rows[0];await audit(Number(user.tenant_id),userId,"login","user",userId,ip(req));ok(res,{id:Number(user.id),email:user.email,display_name:user.display_name,role:user.role})});
app.post("/api/auth/logout",authenticate,async(req,res)=>{await audit(req.user!.tenantId,req.user!.id,"logout","user",req.user!.id,ip(req));await destroySession(req,res);ok(res,{})});
app.get("/api/auth/me",authenticate,(req,res)=>ok(res,req.user));
app.post("/api/auth/change-password",authenticate,async(req,res)=>{const current=String(req.body.current_password||""),next=String(req.body.new_password||"");if(next.length<12)return fail(res,"新密码至少 12 位");const row=(await query<Row>("SELECT password_hash FROM users WHERE id=$1",[req.user!.id])).rows[0];if(!row||!await bcrypt.compare(current,row.password_hash))return fail(res,"当前密码错误",401);const passwordHash=await bcrypt.hash(next,12);await query("UPDATE users SET password_hash=$1 WHERE id=$2",[passwordHash,req.user!.id]);await query("DELETE FROM sessions WHERE user_id=$1",[req.user!.id]);await audit(req.user!.tenantId,req.user!.id,"change_password","user",req.user!.id,ip(req));res.clearCookie("storemap_session",{path:"/"});ok(res,{},"密码已修改，请重新登录")});

app.use("/api",authenticate);
app.get("/api/admin/users",requireAdmin,async(req,res)=>{const rows=(await query<Row>("SELECT id,email,display_name,role,active,created_at FROM users WHERE tenant_id=$1 ORDER BY id",[req.user!.tenantId])).rows;ok(res,rows)});
app.post("/api/admin/users",requireAdmin,async(req,res)=>{const email=clean(req.body.email).toLowerCase(),displayName=clean(req.body.display_name),password=String(req.body.password||""),role=req.body.role==="admin"?"admin":"member";if(!email||!displayName||password.length<10)return fail(res,"姓名、邮箱必填，密码至少 10 位");const passwordHash=await bcrypt.hash(password,12);try{const row=(await query<Row>("INSERT INTO users(tenant_id,email,display_name,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,email,display_name,role,active,created_at",[req.user!.tenantId,email,displayName,passwordHash,role])).rows[0];await audit(req.user!.tenantId,req.user!.id,"create_user","user",row.id,ip(req),{email,role});ok(res,row,"用户已创建",201)}catch{fail(res,"邮箱已存在",409)}});

app.get("/api/poi-categories",(_req,res)=>ok(res,Object.keys(POI_CATEGORY_TYPES).concat("竞品门店").map((name,index)=>({id:index+1,name,display_name:name}))));
app.post("/api/geocode",async(req,res,next)=>{try{ok(res,{candidates:await geocode(req.body)})}catch(error){next(error)}});
app.post("/api/stores/search",async(req,res,next)=>{try{ok(res,{candidates:await searchCandidates(clean(req.body.name),clean(req.body.city),clean(req.body.district),clean(req.body.address))})}catch(error){next(error)}});
app.post("/api/stores/from-geocode",async(req,res)=>{const candidate=req.body.candidate||{},location=Array.isArray(candidate.location)?candidate.location:[null,null],row=(await query<Row>("INSERT INTO stores(tenant_id,created_by,input_name,standard_name,longitude,latitude,province,city,district,address,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'已确认') RETURNING id",[req.user!.tenantId,req.user!.id,clean(req.body.name)||clean(candidate.name),clean(candidate.name),location[0],location[1],clean(candidate.province),clean(candidate.city),clean(candidate.district),clean(candidate.address)])).rows[0];ok(res,{id:Number(row.id)},"门店已创建",201)});
app.post("/api/stores",async(req,res)=>{const candidate=req.body.candidate||{},location=Array.isArray(candidate.location)?candidate.location:[null,null],row=(await query<Row>("INSERT INTO stores(tenant_id,created_by,input_name,standard_name,amap_poi_id,longitude,latitude,province,city,district,address,match_score,match_status,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'已确认') RETURNING id",[req.user!.tenantId,req.user!.id,clean(req.body.name),clean(candidate.name),clean(candidate.id),location[0],location[1],clean(candidate.province),clean(candidate.city),clean(candidate.district),clean(candidate.address),Number(candidate.score||0),clean(candidate.status)])).rows[0];ok(res,{id:Number(row.id)},"门店已创建",201)});
app.post("/api/stores/:id/confirm",async(req,res)=>{const result=await query("SELECT id FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id]);if(!result.rowCount)return fail(res,"门店不存在",404);ok(res,{id:Number(req.params.id)})});

app.post("/api/stores/:id/poi-search",async(req,res,next)=>{try{const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store||store.longitude==null)return fail(res,"请先确认门店位置");const categories=Array.isArray(req.body.categories)?req.body.categories.map(clean):["住宅小区","幼儿园","小学"],radii=Array.isArray(req.body.radii)?req.body.radii.map(Number):[500],job=(await query<Row>("INSERT INTO jobs(tenant_id,created_by,status,total_stores,matched_stores,config_json,stage,control) VALUES($1,$2,'正在查询POI',1,1,$3,'analysis','run') RETURNING id",[req.user!.tenantId,req.user!.id,{categories,radii}])).rows[0],jobId=Number(job.id);await query("UPDATE stores SET job_id=$1 WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[jobId,store.id,req.user!.tenantId,req.user!.id]);const result=await enqueueAndWait<{pois:Poi[];analysis:Row}>("analyze-single",{tenantId:req.user!.tenantId,userId:req.user!.id,storeId:Number(store.id),categories,radii});await query("UPDATE jobs SET status='已完成',processed_stores=1,success_stores=1,control='idle',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,req.user!.tenantId,req.user!.id]);ok(res,{job_id:jobId,pois:result.pois})}catch(error){next(error)}});
app.post("/api/stores/:id/business-district-analysis",async(req,res)=>{const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);const job=store.job_id?(await query<Row>("SELECT config_json FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[store.job_id,req.user!.tenantId,req.user!.id])).rows[0]:null,radii=Array.isArray(req.body.radii)?req.body.radii.map(Number):[500],categories=Array.isArray(job?.config_json?.categories)?job.config_json.categories.map(String):[];const analysis=createAnalysis(store,(store.pois_json||[]) as Poi[],radii,categories);await query("UPDATE stores SET analysis_json=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[JSON.stringify(analysis),store.id,req.user!.tenantId,req.user!.id]);ok(res,analysis)});
app.post("/api/stores/:id/ai-analysis",async(req,res,next)=>{try{const store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!store)return fail(res,"门店不存在",404);const job=store.job_id?(await query<Row>("SELECT config_json FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[store.job_id,req.user!.tenantId,req.user!.id])).rows[0]:null,radii=Array.isArray(req.body.radii)&&req.body.radii.length?req.body.radii.map(Number):(job?.config_json?.radii||[500]),result=await enqueueAndWait("ai-single",{tenantId:req.user!.tenantId,userId:req.user!.id,storeId:Number(store.id),radii});ok(res,result,"AI 人群画像已生成")}catch(error){next(error)}});
app.get("/api/stores/:id/ai-analyses",async(req,res)=>{const rows=(await query<Row>("SELECT * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=$3 ORDER BY id DESC LIMIT 30",[req.user!.tenantId,req.user!.id,req.params.id])).rows;ok(res,rows.map(serializeAi))});

const aliases:Record<string,string[]>={name:["门店名称","店名","名称","门店"],province:["省份","省"],city:["城市","市"],district:["区县","区","县"],address:["详细地址","地址","门店地址"],code:["门店编号","编号","编码"],brand:["品牌"],remark:["备注"]};
const headerMap=(headers:string[])=>{const mapping:Record<string,string>={};for(const [field,names] of Object.entries(aliases)){const found=headers.find(header=>names.some(name=>header.trim()===name));if(found)mapping[field]=found}return mapping};
function decodeUploadFilename(value:unknown){const filename=clean(value);if(!/[\u00c0-\u00ff]/.test(filename))return filename;const decoded=Buffer.from(filename,"latin1").toString("utf8");return decoded.includes("\uFFFD")?filename:decoded}
async function readImportRows(file:Express.Multer.File){return parseImportRows(file.buffer,decodeUploadFilename(file.originalname)) as Row[]}
app.get("/api/import/template",async(_req,res,next)=>{try{const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("门店导入模板"),headers=["门店名称","省份","城市","区县","详细地址","门店编号","品牌","备注"];sheet.addRow(headers);sheet.addRow(["示例门店","湖北省","武汉市","洪山区","示例路1号","WH001","零食很忙",""]);sheet.getRow(1).font={bold:true};sheet.columns=headers.map(()=>({width:18}));const buffer=Buffer.from(await workbook.xlsx.writeBuffer());res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",'attachment; filename="store-import-template.xlsx"');res.send(buffer)}catch(error){next(error)}});
app.post("/api/import/preview",upload.single("file"),async(req,res,next)=>{try{if(!req.file)return fail(res,"请选择 Excel 或 CSV 文件");const rows=await readImportRows(req.file),headers=rows.length?Object.keys(rows[0]):[],mapping=headerMap(headers),seen=new Set<string>();let duplicates=0;const selectable=rows.slice(0,5000).map((row,index)=>{const name=clean(row[mapping.name]),address=clean(row[mapping.address]),issues:string[]=[];if(!name&&!address)issues.push("缺少门店名称或详细地址");const key=`${name}|${address}`.toLowerCase();if(key&&seen.has(key)){issues.push("重复门店");duplicates++}if(key)seen.add(key);return {...row,_row_number:index+2,_valid:issues.length===0,_issues:issues}});ok(res,{filename:decodeUploadFilename(req.file.originalname),file_size:req.file.size,headers,mapping,rows:selectable.slice(0,100),all_rows:rows,selectable_rows:selectable,total_rows:rows.length,valid_rows:selectable.filter(row=>row._valid).length,invalid_rows:selectable.filter(row=>!row._valid).length,duplicate_rows:duplicates,warnings:rows.length>5000?["仅处理前 5000 行"]:[]},"文件解析成功")}catch(error){next(error)}});
app.post("/api/import/confirm",async(req,res)=>{const rows=Array.isArray(req.body.rows)?req.body.rows:[],mapping=req.body.mapping||{},config=req.body.config||{};if(!rows.length)return fail(res,"请至少选择一家门店");const client=await pool.connect();try{await client.query("BEGIN");const job=(await client.query<Row>("INSERT INTO jobs(tenant_id,created_by,filename,status,total_stores,config_json,stage,control) VALUES($1,$2,$3,'等待开始匹配',$4,$5,'match','idle') RETURNING id",[req.user!.tenantId,req.user!.id,clean(req.body.filename),rows.length,config])).rows[0];for(const row of rows)await client.query("INSERT INTO stores(tenant_id,created_by,job_id,input_name,province,city,district,address,user_code,brand,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'等待匹配')",[req.user!.tenantId,req.user!.id,job.id,clean(row[mapping.name]),clean(row[mapping.province]),clean(row[mapping.city]),clean(row[mapping.district]),clean(row[mapping.address]),clean(row[mapping.code]),clean(row[mapping.brand])]);await client.query("COMMIT");ok(res,{job_id:Number(job.id),status:"等待开始匹配"},"批量任务创建成功",201)}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});

app.get("/api/analysis-jobs",async(req,res)=>{const rows=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 ORDER BY id DESC LIMIT 100",[req.user!.tenantId,req.user!.id])).rows;ok(res,rows.map(serializeJob))});
app.get("/api/analysis-jobs/:id",async(req,res)=>{const row=await ownedJob(req);if(row)ok(res,serializeJob(row));else fail(res,"任务不存在",404)});
app.get("/api/analysis-jobs/:id/stores",async(req,res)=>{if(!await ownedJob(req))return fail(res,"任务不存在",404);const rows=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 ORDER BY id",[req.params.id,req.user!.tenantId,req.user!.id])).rows;ok(res,rows.map(row=>({store:serializeStore(row),status:row.status,poi_summary:createSummary((row.pois_json||[]) as Poi[]),has_profile:Boolean(row.analysis_json),error_message:row.error_message||""})))});
app.get("/api/analysis-jobs/:id/stores/:storeId",async(req,res)=>{const job=await ownedJob(req),store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND job_id=$2 AND tenant_id=$3 AND created_by=$4",[req.params.storeId,req.params.id,req.user!.tenantId,req.user!.id])).rows[0];if(!job||!store)return fail(res,"门店不存在",404);const pois=(store.pois_json||[]) as Poi[];ok(res,{job:serializeJob(job),store:serializeStore(store),status:store.status,pois,poi_summary:createSummary(pois),analysis:store.analysis_json||null,disclaimer:"本分析仅反映高德POI设施分布及其代理推断。"})});
app.get("/api/analysis-jobs/:id/business-district-results",async(req,res)=>{
  if(!await ownedJob(req))return fail(res,"任务不存在",404);
  const rows=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND analysis_json IS NOT NULL ORDER BY id",[req.params.id,req.user!.tenantId,req.user!.id])).rows;
  const data=rows.map(row=>({...(row.analysis_json||{}),store:serializeStore(row),poi_summary:createSummary((row.pois_json||[]) as Poi[])}));
  ok(res,data);
});
app.post("/api/analysis-jobs/:id/start-matching",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE jobs SET status='已进入匹配队列',control='run',stage='match',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add("match-batch",{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,status:"已进入匹配队列",control:"run",stage:"match"}),"已进入连续匹配队列")});
app.post("/api/analysis-jobs/:id/start-analysis",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE jobs SET status='已进入分析队列',control='run',stage='analysis',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add("analyze-batch",{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,status:"已进入分析队列",control:"run",stage:"analysis"}),"已进入连续分析队列")});
app.post("/api/analysis-jobs/:id/:action",async(req,res,next)=>{if(!["pause","end"].includes(req.params.action))return next();const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const pause=req.params.action==="pause";await query("UPDATE jobs SET status=$1,control=$2,updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND created_by=$5",[pause?"已暂停":"已结束",pause?"pause":"end",job.id,req.user!.tenantId,req.user!.id]);ok(res,serializeJob({...job,status:pause?"已暂停":"已结束",control:pause?"pause":"end"}))});
app.post("/api/analysis-jobs/:id/resume",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const name=job.stage==="analysis"?"analyze-batch":"match-batch";await query("UPDATE jobs SET control='run',status=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[job.stage==="analysis"?"已进入分析队列":"已进入匹配队列",job.id,req.user!.tenantId,req.user!.id]);await taskQueue.add(name,{jobId:Number(job.id),tenantId:req.user!.tenantId,userId:req.user!.id});ok(res,serializeJob({...job,control:"run"}),"任务已继续")});
app.post("/api/analysis-jobs/:id/retry",async(req,res)=>{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);await query("UPDATE stores SET status=CASE WHEN longitude IS NULL THEN '等待匹配' ELSE '已确认' END,error_message=NULL WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND status IN ('匹配失败','分析失败')",[job.id,req.user!.tenantId,req.user!.id]);await query("UPDATE jobs SET status='等待继续匹配',control='idle',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.id,req.user!.tenantId,req.user!.id]);ok(res,serializeJob({...job,status:"等待继续匹配",control:"idle"}))});
app.post("/api/analysis-jobs/:id/ai-comparison",async(req,res,next)=>{try{const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const storeIds=[...new Set((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number))];if(storeIds.length<2||storeIds.length>10)return fail(res,"请选择 2–10 家门店进行 AI 对比");const count=await query("SELECT id FROM stores WHERE tenant_id=$1 AND created_by=$2 AND job_id=$3 AND id=ANY($4::bigint[])",[req.user!.tenantId,req.user!.id,job.id,storeIds]);if(count.rowCount!==storeIds.length)return fail(res,"部分门店不存在或无权访问",403);const result=await enqueueAndWait<Record<string,unknown>>("ai-comparison",{tenantId:req.user!.tenantId,userId:req.user!.id,jobId:Number(job.id),storeIds,radii:job.config_json?.radii||[500]});ok(res,{...result,store_labels:storeIds.map((storeId,index)=>({store_id:storeId,label:`门店${String.fromCharCode(65+index)}`}))},"多店 AI 对比已生成")}catch(error){next(error)}});
app.get("/api/analysis-jobs/:id/ai-comparisons",async(req,res)=>{if(!await ownedJob(req))return fail(res,"任务不存在",404);const rows=(await query<Row>("SELECT * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='comparison' AND job_id=$3 ORDER BY id DESC LIMIT 30",[req.user!.tenantId,req.user!.id,req.params.id])).rows;ok(res,rows.map(serializeAi))});
app.get("/api/batch-export/options",async(req,res)=>{const jobs=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 ORDER BY id DESC LIMIT 100",[req.user!.tenantId,req.user!.id])).rows;ok(res,{jobs:jobs.map(serializeJob),fields:EXPORT_BASE_FIELDS,required_fields:[{id:"store_name",label:"门店名称"},{id:"store_address",label:"门店地址"}],sheet_options:[{id:"poi_details",label:"POI 明细"},{id:"failures",label:"失败与未完成门店"},{id:"notes",label:"导出说明"}]})});
app.post("/api/batch-export",async(req,res,next)=>{try{
  const jobIds:number[]=[...new Set<number>((Array.isArray(req.body.job_ids)?req.body.job_ids:[]).map(Number).filter(Number.isInteger))];
  if(!jobIds.length||jobIds.length>100)return fail(res,"请选择 1–100 个分析任务");
  const jobs=(await query<Row>("SELECT * FROM jobs WHERE tenant_id=$1 AND created_by=$2 AND id=ANY($3::bigint[]) ORDER BY id",[req.user!.tenantId,req.user!.id,jobIds])).rows;
  if(jobs.length!==jobIds.length)return fail(res,"部分任务不存在或无权访问",403);
  const availableRadii:number[]=[...new Set<number>(jobs.flatMap(job=>Array.isArray(job.config_json?.radii)?job.config_json.radii.map(Number):[]))].sort((a,b)=>a-b);
  const availableCategories:string[]=[...new Set<string>(jobs.flatMap(job=>Array.isArray(job.config_json?.categories)?job.config_json.categories.map(String):[]))];
  const radii:number[]=[...new Set<number>((Array.isArray(req.body.radii)?req.body.radii:availableRadii).map(Number))].filter(radius=>availableRadii.includes(radius));
  const categories:string[]=[...new Set<string>((Array.isArray(req.body.categories)?req.body.categories:availableCategories).map(clean))].filter(category=>availableCategories.includes(category));
  if(!radii.length||!categories.length)return fail(res,"所选任务没有可导出的分析半径或 POI 分类");
  const knownFields=new Set<string>(EXPORT_BASE_FIELDS.map(field=>field.id)),fields:string[]=[...new Set<string>((Array.isArray(req.body.fields)?req.body.fields:[]).map(clean))].filter(field=>knownFields.has(field));
  const storeIds:number[]=[...new Set<number>((Array.isArray(req.body.store_ids)?req.body.store_ids:[]).map(Number).filter(Number.isInteger))],params:unknown[]=[req.user!.tenantId,req.user!.id,jobIds],storeClause=storeIds.length?" AND s.id=ANY($4::bigint[])":"",storeParams=storeIds.length?[...params,storeIds]:params;
  const rows=(await query<Row>(`SELECT s.*,j.config_json AS job_config,j.filename AS job_filename FROM stores s JOIN jobs j ON j.id=s.job_id WHERE s.tenant_id=$1 AND s.created_by=$2 AND j.created_by=$2 AND s.job_id=ANY($3::bigint[])${storeClause} ORDER BY s.job_id,s.id`,storeParams)).rows;
  if(storeIds.length&&rows.length!==storeIds.length)return fail(res,"部分门店不存在或无权访问",403);if(!rows.length)return fail(res,"所选任务没有可导出的门店");if(rows.length>5000)return fail(res,"单次最多导出 5,000 家门店");
  const aiRows=(await query<Row>("SELECT DISTINCT ON (store_id) * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=ANY($3::bigint[]) ORDER BY store_id,created_at DESC",[req.user!.tenantId,req.user!.id,rows.map(row=>Number(row.id))])).rows;
  const selection:ExportSelection={jobIds,storeIds,fields,radii,categories,includePoiDetails:Boolean(req.body.include_poi_details),includeFailures:req.body.include_failures!==false,includeNotes:req.body.include_notes!==false},filename=`门店POI批量导出_${new Date().toISOString().slice(0,10)}.xlsx`,buffer=await buildBatchExportWorkbook(rows,aiRows,selection,{userEmail:req.user!.email,jobNames:jobs.map(job=>decodeUploadFilename(job.filename)||`任务#${job.id}`)});
  await audit(req.user!.tenantId,req.user!.id,"batch_export","jobs",jobIds.join(","),ip(req),{store_count:rows.length,radii,categories,fields});sendXlsx(res,buffer,filename);
}catch(error){next(error)}});
app.get(["/api/analysis-jobs/:id/export","/api/analysis-jobs/:id/business-district-export","/api/analysis-jobs/:id/stores/:storeId/export"],exportJob);

async function ownedJob(req:Request){return (await query<Row>("SELECT * FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[req.params.id,req.user!.tenantId,req.user!.id])).rows[0]}
function serializeJob(row:Row){const total=Number(row.total_stores||0),stage=row.stage||"match",processed=Number(row.processed_stores||0),stageTotal=stage==="analysis"?Number(row.matched_stores||total):total;return {id:Number(row.id),filename:decodeUploadFilename(row.filename),status:row.status,total_stores:total,processed_stores:processed,matched_stores:Number(row.matched_stores||0),pending_stores:Math.max(0,total-processed),success_stores:Number(row.success_stores||0),failed_stores:Number(row.failed_stores||0),config:row.config_json||{},stage,control:row.control||"idle",stage_total:stageTotal,stage_processed:processed,progress_percent:Math.round(processed/Math.max(1,stageTotal)*100),current_store:row.current_store||"",created_at:new Date(row.created_at).toISOString(),updated_at:new Date(row.updated_at).toISOString()}}
function serializeStore(row:Row){return {id:Number(row.id),input_name:row.input_name,standard_name:row.standard_name,amap_poi_id:row.amap_poi_id,longitude:row.longitude==null?null:Number(row.longitude),latitude:row.latitude==null?null:Number(row.latitude),province:row.province||"",city:row.city||"",district:row.district||"",address:row.address||"",match_score:row.match_score==null?null:Number(row.match_score),match_status:row.match_status||"",location_source:row.amap_poi_id?"高德POI":"待定位"}}
function serializeAi(row:Row){return {id:Number(row.id),scope:row.scope,job_id:row.job_id==null?null:Number(row.job_id),store_id:row.store_id==null?null:Number(row.store_id),store_ids:row.store_ids_json||[],result:row.result_json||{},model:row.model,prompt_version:row.prompt_version,usage:{input_tokens:Number(row.input_tokens||0),output_tokens:Number(row.output_tokens||0),total_tokens:Number(row.total_tokens||0)},created_at:new Date(row.created_at).toISOString()}}
function sendXlsx(res:Response,buffer:Buffer,filename:string){res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",`attachment; filename="store-poi-export.xlsx"; filename*=UTF-8''${encodeURIComponent(filename)}`);res.setHeader("Access-Control-Expose-Headers","Content-Disposition");res.send(buffer)}
async function exportJob(req:Request,res:Response){const job=await ownedJob(req);if(!job)return fail(res,"任务不存在",404);const params:unknown[]=[req.user!.tenantId,req.user!.id,req.params.id],storeClause=req.params.storeId?" AND s.id=$4":"",rows=(await query<Row>(`SELECT s.*,j.config_json AS job_config,j.filename AS job_filename FROM stores s JOIN jobs j ON j.id=s.job_id WHERE s.tenant_id=$1 AND s.created_by=$2 AND j.created_by=$2 AND s.job_id=$3${storeClause} ORDER BY s.id`,req.params.storeId?[...params,req.params.storeId]:params)).rows;if(!rows.length)return fail(res,"没有可导出的门店",404);const aiRows=(await query<Row>("SELECT DISTINCT ON (store_id) * FROM ai_analyses WHERE tenant_id=$1 AND created_by=$2 AND scope='single' AND store_id=ANY($3::bigint[]) ORDER BY store_id,created_at DESC",[req.user!.tenantId,req.user!.id,rows.map(row=>Number(row.id))])).rows,config=job.config_json||{},selection:ExportSelection={jobIds:[Number(job.id)],storeIds:req.params.storeId?[Number(req.params.storeId)]:[],fields:["city","district","longitude","latitude","status","match_score","poi_total","business_district_type","main_audience","age_ranges","consumption_index","analysis_confidence","ai_summary","ai_confidence","error_message"],radii:Array.isArray(config.radii)?config.radii.map(Number):[500],categories:Array.isArray(config.categories)?config.categories.map(String):[],includePoiDetails:true,includeFailures:true,includeNotes:true},buffer=await buildBatchExportWorkbook(rows,aiRows,selection,{userEmail:req.user!.email,jobNames:[decodeUploadFilename(job.filename)||`任务#${job.id}`]});sendXlsx(res,buffer,req.params.storeId?`门店报告_${rows[0].input_name}.xlsx`:`任务${job.id}_门店POI报告.xlsx`)}

app.use((error:unknown,req:Request,res:Response,next:unknown)=>{void next;req.log.error(error);fail(res,error instanceof Error?error.message:"服务器错误",500,"SERVER_ERROR")});
const port=Number(process.env.API_PORT||8000),server=app.listen(port,"0.0.0.0",()=>console.log(`Node API listening on ${port}`));
async function stop(){server.close();await Promise.allSettled([redis.quit(),taskQueue.close(),pool.end()]);process.exit(0)}process.on("SIGTERM",stop);process.on("SIGINT",stop);
