/* eslint-disable @typescript-eslint/no-explicit-any */
import { callDeepSeek, type AggregateStore } from "../app/api/deepseek.js";
import { query } from "./db.js";

export type Row=Record<string,any>;
export type Poi={id:string;name:string;category:string;type:string;typecode:string;address:string;distance:number;location:[number,number];distance_bucket:string};
export const POI_CATEGORY_TYPES:Record<string,string>={"住宅小区":"120302","幼儿园":"141204","小学":"141203","中学":"141202","购物中心":"060101","超市":"060400","便利店":"060200","医院":"090100","药店":"090601","公园":"110101","地铁站":"150500","公交站":"150700"};
let lastAmap=0;
export const clean=(value:unknown)=>String(value??"").trim();
const normalize=(value:string)=>value.toLowerCase().replace(/[\s（）()·\-_]/g,"").replace(/分店|门店|店$/g,"");
const parseLocation=(value:unknown):[number,number]|null=>{const parts=clean(value).split(",").map(Number);return parts.length>=2&&parts.every(Number.isFinite)?[parts[0],parts[1]]:null};
const haversine=(a:[number,number],b:[number,number])=>{const r=6371000,toRad=(n:number)=>n*Math.PI/180,dLat=toRad(b[1]-a[1]),dLng=toRad(b[0]-a[0]),x=Math.sin(dLat/2)**2+Math.cos(toRad(a[1]))*Math.cos(toRad(b[1]))*Math.sin(dLng/2)**2;return Math.round(2*r*Math.asin(Math.sqrt(x)))};
const distanceBucket=(distance:number,radii:number[])=>{const sorted=[...radii].sort((a,b)=>a-b),hit=sorted.find(radius=>distance<=radius);return hit?`≤${hit}米`:`>${sorted.at(-1)||500}米`};

async function amap(path:string,params:Record<string,unknown>){
  const key=process.env.AMAP_WEB_SERVICE_KEY;if(!key)throw new Error("高德 Web Service Key 尚未配置");const interval=Math.max(50,Number(process.env.AMAP_REQUEST_INTERVAL_MS||100));
  for(let attempt=0;attempt<3;attempt++){const wait=interval-(Date.now()-lastAmap);if(wait>0)await new Promise(resolve=>setTimeout(resolve,wait));lastAmap=Date.now();const url=new URL(`https://restapi.amap.com${path}`);Object.entries({...params,key}).forEach(([name,value])=>url.searchParams.set(name,String(value)));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Number(process.env.AMAP_REQUEST_TIMEOUT||15)*1000);try{const response=await fetch(url,{signal:controller.signal});const data=await response.json() as Row;if(String(data.status)==="1")return data;const code=clean(data.infocode);if(["10014","10015","10019","10020","10021","10022","10023"].includes(code)&&attempt<2){await new Promise(resolve=>setTimeout(resolve,(attempt+1)*1000));continue}throw new Error(code==="10003"?"高德地图当月调用额度已用完":`高德地图服务不可用：${clean(data.info)||code}`)}finally{clearTimeout(timer)}}throw new Error("高德地图请求失败");
}

export async function searchCandidates(input:string,city="",district="",address=""){
  const data=await amap("/v5/place/text",{keywords:input,region:city||district,city_limit:Boolean(city||district),show_fields:"business,navi",page_size:20,page_num:1}),rows=Array.isArray(data.pois)?data.pois as Row[]:[];
  return rows.map(raw=>{const location=parseLocation(raw.location);if(!location)return null;const name=clean(raw.name),poiCity=clean(raw.cityname||raw.city),poiDistrict=clean(raw.adname||raw.district),a=normalize(input),b=normalize(name);let score=a===b?92:(a.includes(b)||b.includes(a)?78:48);if(city&&poiCity.includes(city.replace(/市$/,"") ))score+=5;if(district&&poiDistrict.includes(district.replace(/[区县]$/,"") ))score+=5;score=Math.min(100,score);return {id:clean(raw.id),name,address:clean(raw.address),province:clean(raw.pname||raw.province),city:poiCity,district:poiDistrict,location,type:clean(raw.type),typecode:clean(raw.typecode),score,status:score>=75?"高置信度":score>=55?"中置信度":"低置信度",reasons:[score>=75?"门店名称与行政区信息较一致":"系统按名称与地址综合排序",...(address?["已参考用户填写的详细地址"]:[])]}}).filter(Boolean).sort((a:any,b:any)=>b.score-a.score);
}

export async function geocode(body:Row){const address=[body.province,body.city,body.district,body.address||body.name].map(clean).join(""),data=await amap("/v3/geocode/geo",{address,city:clean(body.city)}),rows=Array.isArray(data.geocodes)?data.geocodes as Row[]:[];return rows.map((item,index)=>{const location=parseLocation(item.location);return location?{id:`geo-${index}`,name:clean(body.name)||clean(item.formatted_address),formatted_address:clean(item.formatted_address),address:clean(item.formatted_address),province:clean(item.province),city:clean(item.city)||clean(body.city),district:clean(item.district),adcode:clean(item.adcode),location,type:"地址定位",typecode:"",score:70,status:"地址候选",reasons:["根据详细地址完成地理编码"],source:"amap_geocode"}:null}).filter(Boolean)};

export async function searchPois(store:Row,categories:string[],radii:number[]){const maxRadius=Math.max(...radii),origin:[number,number]=[Number(store.longitude),Number(store.latitude)],items:Poi[]=[];for(const category of categories){const types=POI_CATEGORY_TYPES[category]||"",params:Row={location:origin.join(","),radius:maxRadius,sortrule:"distance",page_size:25,page_num:1,show_fields:"business,navi"};if(types)params.types=types;else params.keywords=category==="竞品门店"?"零食很忙|赵一鸣零食|来伊份|良品铺子":category;const data=await amap("/v5/place/around",params);for(const raw of (Array.isArray(data.pois)?data.pois as Row[]:[])){const location=parseLocation(raw.location);if(!location)continue;const distance=Number(raw.distance)||haversine(origin,location);items.push({id:clean(raw.id),name:clean(raw.name),category,type:clean(raw.type),typecode:clean(raw.typecode),address:clean(raw.address),distance,location,distance_bucket:distanceBucket(distance,radii)})}}const unique=new Map<string,Poi>();for(const item of items){const key=item.id||`${item.name}|${item.location.join(",")}`;if(!unique.has(key))unique.set(key,item)}return [...unique.values()].sort((a,b)=>a.distance-b.distance)}

export function createSummary(pois:Poi[]){const by_category:Record<string,number>={},by_distance:Record<string,number>={};for(const poi of pois){by_category[poi.category]=(by_category[poi.category]||0)+1;by_distance[poi.distance_bucket]=(by_distance[poi.distance_bucket]||0)+1}return {total:pois.length,by_category,by_distance}}

export type BusinessDistrictRadiusRecognition={radius:number;status:"已识别"|"证据不足";is_business_district:boolean|null;conclusion:string;strength:string;type:string;score:number;confidence:string;evidence:string[];missing_categories:string[];metrics:{commercial:number;shopping_centers:number;retail:number;competitors:number;transport:number;diversity:number;evidence_coverage:number}};
export type BusinessDistrictRecognition={method:string;primary_radius:number;by_radius:Record<string,BusinessDistrictRadiusRecognition>;limitations:string[]};

const BUSINESS_EVIDENCE_CATEGORIES=["购物中心","超市","便利店","地铁站","公交站","竞品门店"];
function categoryCounts(pois:Poi[]){const counts:Record<string,number>={};for(const poi of pois)counts[poi.category]=(counts[poi.category]||0)+1;return counts}

export function recognizeBusinessDistrict(pois:Poi[],radii:number[],analyzedCategories:string[]):BusinessDistrictRecognition{
  const normalizedRadii=[...new Set(radii.map(Number).filter(radius=>Number.isFinite(radius)&&radius>0))].sort((a,b)=>a-b),available=new Set(analyzedCategories),coverage=BUSINESS_EVIDENCE_CATEGORIES.filter(category=>available.has(category)).length/BUSINESS_EVIDENCE_CATEGORIES.length,missing=BUSINESS_EVIDENCE_CATEGORIES.filter(category=>!available.has(category));
  const byRadius:Record<string,BusinessDistrictRadiusRecognition>={};
  for(const radius of normalizedRadii){
    const inside=pois.filter(poi=>Number(poi.distance)<=radius),counts=categoryCounts(inside),shoppingCenters=counts["购物中心"]||0,retail=(counts["超市"]||0)+(counts["便利店"]||0),competitors=counts["竞品门店"]||0,transport=(counts["地铁站"]||0)+(counts["公交站"]||0),commercial=shoppingCenters+retail+competitors,diversity=["购物中心","超市","便利店","竞品门店"].filter(category=>(counts[category]||0)>0).length,areaScale=Math.min(1,(500/radius)**2),normalizedRetail=retail*areaScale,normalizedCompetitors=competitors*areaScale,normalizedTransport=transport*areaScale;
    const score=Math.min(100,Math.round((shoppingCenters>0?32:0)+Math.min(25,normalizedRetail*5)+Math.min(12,normalizedCompetitors*4)+Math.min(16,(counts["地铁站"]||0)*12+normalizedTransport*1.5)+Math.min(15,diversity*4)));
    const enoughEvidence=coverage>=0.5&&(commercial+transport)>=2,isBusiness=enoughEvidence?score>=50:null,strength=!enoughEvidence?"证据不足":score>=75?"成熟商圈":score>=60?"成形商圈":score>=50?"初步商圈":"未形成明显商圈",type=shoppingCenters>0||commercial>=6?"商业消费型":transport>commercial?"交通带动型":competitors>=3?"零售聚集型":"社区商业型",confidence=!enoughEvidence?"低":coverage>=0.8&&(commercial+transport)>=8?"较高":coverage>=0.65&&(commercial+transport)>=4?"中":"较低";
    const evidence=[`半径内商业相关 POI ${commercial} 个，其中购物中心 ${shoppingCenters} 个、超市及便利店 ${retail} 个、竞品门店 ${competitors} 个`,`交通 POI ${transport} 个，商业类别覆盖 ${diversity} 类`,`商圈证据分类覆盖率 ${Math.round(coverage*100)}%`];
    byRadius[String(radius)]={radius,status:enoughEvidence?"已识别":"证据不足",is_business_district:isBusiness,conclusion:isBusiness===null?"暂无法判断":isBusiness?"是，周边已呈现商圈特征":"否，暂未识别到明显商圈",strength,type,score,confidence,evidence,missing_categories:missing,metrics:{commercial,shopping_centers:shoppingCenters,retail,competitors,transport,diversity,evidence_coverage:Math.round(coverage*100)}};
  }
  const primaryRadius=normalizedRadii.includes(500)?500:(normalizedRadii[0]||500);
  return {method:"基于高德 POI 的规则识别",primary_radius:primaryRadius,by_radius:byRadius,limitations:["结论不等同于高德或政府发布的官方商圈边界。","未使用真实客流、订单、会员、租金或交易数据。","未勾选的证据分类不会被推定为 0；分类覆盖不足时返回证据不足。"]};
}

export function createAnalysis(store:Row,pois:Poi[],radii:number[]){const counts=createSummary(pois).by_category,residential=counts["住宅小区"]||0,education=(counts["幼儿园"]||0)+(counts["小学"]||0),commercial=(counts["购物中心"]||0)+(counts["超市"]||0)+(counts["便利店"]||0),traffic=(counts["地铁站"]||0)+(counts["公交站"]||0),competitors=counts["竞品门店"]||0,total=pois.length,levelScore=Math.min(100,Math.round(total*2.2+commercial*3+traffic*2)),fitScore=Math.min(100,Math.round(residential*5+education*6+commercial*3+traffic*2-Math.min(20,competitors*4))),type=education>=Math.max(commercial,traffic)?"社区家庭型":commercial>=education?"商业消费型":traffic>2?"交通通勤型":"综合生活型",ageSegments=[{label:"学生与青少年",age_range:"6–18岁",index:Math.min(100,education*16),basis:`教育设施 ${education} 个`},{label:"青年与年轻家庭",age_range:"19–35岁",index:Math.min(100,35+commercial*7+traffic*5),basis:`商业设施 ${commercial} 个、交通设施 ${traffic} 个`},{label:"家庭消费人群",age_range:"30–45岁",index:Math.min(100,30+residential*10+education*5),basis:`住宅小区 ${residential} 个`},{label:"中老年常住人群",age_range:"46岁以上",index:Math.min(100,20+residential*7),basis:`住宅设施 ${residential} 个`}].sort((a,b)=>b.index-a.index),consumptionIndex=Math.min(100,Math.round(35+commercial*7+traffic*3)),created=new Date().toISOString();return {id:Number(store.id),analysis_version:"server-v1",radius_config:radii,confidence_level:total>=15?"中":total>=5?"较低":"低",business_area:{name:clean(store.district)||clean(store.city)||"门店周边",source:"高德POI代理判断",confidence:total>=15?"中":"低"},business_district_type:{type,scores:{社区:residential*10+education*6,商业:commercial*10,交通:traffic*12},confidence:total>=15?"中":"低"},level:{level:levelScore>=70?"成熟":levelScore>=45?"成长":"基础",score:levelScore,mode:"POI代理评分"},fit:{score:fitScore,level:fitScore>=70?"较高":fitScore>=45?"中等":"较低"},competition:{score:Math.min(100,competitors*18),level:competitors>=4?"较高":competitors>=2?"中等":"较低"},feature_vector:{layers:{"500m":{total,density:total,counts,nearest:{}}},level_indicators:{poi_total:total},fit_components:{residential,education,commercial,traffic}},audience_profile:{method:"基于周边设施结构的代理推断",confidence:total>=15?"中":"低",primary_groups:ageSegments.slice(0,2),age_segments:ageSegments,consumption_power:{level:consumptionIndex>=70?"中高":consumptionIndex>=45?"中等":"偏基础",index:consumptionIndex,confidence:total>=15?"中":"低",basis:`商业 ${commercial} 个、交通 ${traffic} 个；不等同于真实收入统计`},mall_profile:{level:(counts["购物中心"]||0)>=2?"区域商业较集中":(counts["购物中心"]||0)?"存在商场辐射":"社区商业为主",confidence:"低",sample_count:counts["购物中心"]||0,sample_names:[],basis:"依据购物中心POI数量推断"},summary:[`周边更可能以${ageSegments[0].label}和${ageSegments[1].label}为主要潜在人群。`],evidence:[`共获取 ${total} 个有效 POI`],limitations:["结果是POI环境代理推断，不是人口普查、客流或收入数据。"]},strengths:[total>=15?"周边设施样本较充足":"已形成基础设施样本"],weaknesses:[total<15?"POI样本较少":"缺少真实订单和会员数据"],warning_messages:["请勿将画像直接解释为实际人口比例或消费收入"],disclaimer:"本分析仅反映高德POI设施分布及其代理推断。",created_at:created,poi_summary:createSummary(pois)}}

export function createEnhancedAnalysis(store:Row,pois:Poi[],radii:number[],analyzedCategories:string[]=[]){
  const inferredCategories=[...new Set(pois.map(poi=>poi.category))],categories=analyzedCategories.length?analyzedCategories:inferredCategories,base=createAnalysis(store,pois,radii),counts=createSummary(pois).by_category,middleSchools=counts["中学"]||0,education=(counts["幼儿园"]||0)+(counts["小学"]||0)+middleSchools,recognition=recognizeBusinessDistrict(pois,radii,categories),primary=recognition.by_radius[String(recognition.primary_radius)],layers:Record<string,Row>={};
  for(const radius of [...new Set(radii)].sort((a,b)=>a-b)){const inside=pois.filter(poi=>poi.distance<=radius);layers[String(radius)]={total:inside.length,density:inside.length,counts:categoryCounts(inside),nearest:{}}}
  const scores={...base.business_district_type.scores,教育:Math.min(100,education*12),商业:Math.min(100,primary?.score??base.business_district_type.scores.商业)},ageSegments=base.audience_profile.age_segments.map(segment=>segment.label==="学生与青少年"?{...segment,index:Math.min(100,segment.index+middleSchools*16),basis:`幼儿园、小学及中学共 ${education} 个，其中中学 ${middleSchools} 个`}:segment).sort((a,b)=>b.index-a.index);
  return {...base,analysis_version:"server-v2",business_area:{name:`门店周边${recognition.primary_radius}米`,source:recognition.method,confidence:primary?.confidence||"低"},business_district_type:{type:primary?.is_business_district?primary.type:base.business_district_type.type,scores,confidence:primary?.confidence||base.business_district_type.confidence},business_district_recognition:recognition,feature_vector:{...base.feature_vector,layers,fit_components:{...base.feature_vector.fit_components,education,middle_school:middleSchools}},audience_profile:{...base.audience_profile,age_segments:ageSegments,primary_groups:ageSegments.slice(0,2),evidence:[...base.audience_profile.evidence,`教育设施 ${education} 个，其中中学 ${middleSchools} 个`],limitations:[...base.audience_profile.limitations,...recognition.limitations]},disclaimer:"本分析基于高德 POI 的设施分布和规则识别，不等同于官方商圈边界、真实客流、人口或消费交易数据。"};
}

export function aggregateStore(label:string,pois:Poi[],radii:number[]):AggregateStore{return {label,circles:[...new Set(radii)].sort((a,b)=>a-b).map(radius=>{const inside=pois.filter(poi=>poi.distance<=radius),counts:Record<string,number>={};for(const poi of inside)counts[poi.category]=(counts[poi.category]||0)+1;return {radius,total:inside.length,counts}})}}

export async function generateAi(tenantId:number,createdBy:number,scope:"single"|"comparison",stores:AggregateStore[],jobId:number|null,storeId:number|null,storeIds:number[]){const apiKey=process.env.DEEPSEEK_API_KEY||"";if(!apiKey)throw new Error("DeepSeek API Key 尚未配置");const model=process.env.DEEPSEEK_MODEL||"deepseek-v4-flash",generated=await callDeepSeek({apiKey,apiBaseUrl:process.env.DEEPSEEK_API_BASE_URL||"https://api.deepseek.com",model,scope,stores}),usage=generated.usage,result=await query<{id:number;created_at:string}>("INSERT INTO ai_analyses(tenant_id,created_by,scope,job_id,store_id,store_ids_json,input_json,result_json,model,prompt_version,input_tokens,output_tokens,total_tokens) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id,created_at",[tenantId,createdBy,scope,jobId,storeId,JSON.stringify(storeIds),JSON.stringify({scope,stores}),JSON.stringify(generated.result),model,generated.promptVersion,Number(usage.prompt_tokens||0),Number(usage.completion_tokens||0),Number(usage.total_tokens||0)]),saved=result.rows[0];return {id:Number(saved.id),scope,job_id:jobId,store_id:storeId,store_ids:storeIds,result:generated.result,model,prompt_version:generated.promptVersion,usage:{input_tokens:Number(usage.prompt_tokens||0),output_tokens:Number(usage.completion_tokens||0),total_tokens:Number(usage.total_tokens||0)},created_at:saved.created_at}}
