/* eslint-disable @typescript-eslint/no-explicit-any */
import { Worker, type Job } from "bullmq";
import { query } from "./db.js";
import { aggregateStore, createEnhancedAnalysis as createAnalysis, generateAi, PROFILE_CATEGORIES, resolveStoreCandidates, searchPois, type Poi, type Row } from "./services.js";
import { redisConnection, taskQueue } from "./queue.js";
import { processAiExport } from "./ai-export.js";
import { consumeBackgroundQuota, isQuotaPauseError, processBrandExport, processDiscoveryJob, quotaResumeDelay } from "./brand-library.js";

async function ownerJob(jobId:number,tenantId:number,userId:number){return (await query<Row>("SELECT * FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows[0]}
async function refreshJob(jobId:number,tenantId:number,userId:number,stage:"match"|"analysis"){
  const rows=(await query<{status:string}>("SELECT status FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows,total=rows.length;
  if(stage==="match"){
    const processed=rows.filter(row=>row.status!=="等待匹配").length,matched=rows.filter(row=>["已确认","分析完成","分析失败"].includes(row.status)).length,failed=rows.filter(row=>row.status==="匹配失败").length,review=rows.filter(row=>row.status==="待确认").length;
    await query("UPDATE jobs SET processed_stores=$1,matched_stores=$2,failed_stores=$3,updated_at=NOW() WHERE id=$4 AND tenant_id=$5 AND created_by=$6",[processed,matched,failed,jobId,tenantId,userId]);return {processed,matched,failed,review,total};
  }
  const processed=rows.filter(row=>["分析完成","分析失败"].includes(row.status)).length,success=rows.filter(row=>row.status==="分析完成").length,failed=rows.filter(row=>["匹配失败","分析失败"].includes(row.status)).length;
  await query("UPDATE jobs SET processed_stores=$1,success_stores=$2,failed_stores=$3,updated_at=NOW() WHERE id=$4 AND tenant_id=$5 AND created_by=$6",[processed,success,failed,jobId,tenantId,userId]);return {processed,success,failed,total};
}

async function matchBatch(jobId:number,tenantId:number,userId:number){
  if(!await ownerJob(jobId,tenantId,userId))throw new Error("任务不存在或无权访问");
  await query("UPDATE jobs SET status='正在匹配门店',stage='match',control='run',processed_stores=0,current_store='',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId]);
  const stores=(await query<Row>("SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND status IN ('等待匹配','匹配失败') ORDER BY id",[jobId,tenantId,userId])).rows;
  for(const store of stores){const control=(await query<{control:string}>("SELECT control FROM jobs WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId])).rows[0]?.control;if(control!=="run")break;await query("UPDATE jobs SET current_store=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[store.input_name,jobId,tenantId,userId]);try{const candidates=await resolveStoreCandidates({...store.search_input_json,originalName:store.input_name,searchName:store.search_input_json?.searchName||store.input_name,province:store.province,city:store.city,district:store.district,address:store.address,poiId:store.amap_poi_id,longitude:store.longitude,latitude:store.latitude}) as any[],top=candidates[0];if(!top)throw new Error("高德未返回有效候选");if(top.auto_confirm)await query("UPDATE stores SET standard_name=$1,amap_poi_id=$2,longitude=$3,latitude=$4,province=$5,city=$6,district=$7,address=$8,match_score=$9,match_status=$10,status='已确认',match_candidates_json=$11,error_message=NULL,confirmation_method='系统高置信度自动确认',updated_at=NOW() WHERE id=$12 AND tenant_id=$13 AND created_by=$14",[top.name,top.id,top.location[0],top.location[1],top.province||store.province,top.city||store.city,top.district||store.district,top.address||store.address,top.score,top.status,candidates,store.id,tenantId,userId]);else await query("UPDATE stores SET match_score=$1,match_status=$2,status='待确认',match_candidates_json=$3,error_message=$4,updated_at=NOW() WHERE id=$5 AND tenant_id=$6 AND created_by=$7",[top.score,top.status,candidates,"已保留候选，请人工确认后再分析",store.id,tenantId,userId])}catch(error){await query("UPDATE stores SET status='匹配失败',error_message=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[error instanceof Error?error.message:"匹配失败",store.id,tenantId,userId])}await refreshJob(jobId,tenantId,userId,"match")}
  const counts=await refreshJob(jobId,tenantId,userId,"match"),review=(await query("SELECT COUNT(*)::int AS count FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND status='待确认'",[jobId,tenantId,userId])).rows[0]?.count||0,state=await ownerJob(jobId,tenantId,userId);if(state?.control==="run")await query("UPDATE jobs SET status=$1,control='idle',current_store='',updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[counts.failed?"匹配部分失败":"匹配完成",jobId,tenantId,userId]);return {...counts,review};
}

async function analyzeBatch(jobId:number,tenantId:number,userId:number){
  const job=await ownerJob(jobId,tenantId,userId);if(!job)throw new Error("任务不存在或无权访问");if(job.control==="pause"&&job.status==="已暂停")return;const config=job.config_json||{},requested:string[]=Array.isArray(config.categories)&&config.categories.length?config.categories.map(String):["住宅小区","幼儿园","小学"],categories:string[]=[...new Set<string>(config.generate_profile?[...requested,...PROFILE_CATEGORIES]:requested)],radii:number[]=Array.isArray(config.radii)&&config.radii.length?config.radii.map(Number):[500];
  if(categories.length!==requested.length)await query("UPDATE jobs SET config_json=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[{...config,categories},jobId,tenantId,userId]);
  await query("UPDATE jobs SET status='正在完整分析',stage='analysis',control='run',processed_stores=0,success_stores=0,current_store='',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId]);
  const statusClause=config.brand_library?"('已确认','分析失败')":"('已确认','分析失败','分析完成')",stores=(await query<Row>(`SELECT * FROM stores WHERE job_id=$1 AND tenant_id=$2 AND created_by=$3 AND longitude IS NOT NULL AND status IN ${statusClause} ORDER BY id`,[jobId,tenantId,userId])).rows;
  for(const store of stores){const state=await ownerJob(jobId,tenantId,userId);if(state?.control!=="run")break;await query("UPDATE jobs SET current_store=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[store.input_name,jobId,tenantId,userId]);try{const quotaHook=config.brand_library?()=>consumeBackgroundQuota(tenantId).then(()=>undefined):undefined,pois=await searchPois(store,categories,radii,quotaHook),analysis=createAnalysis(store,pois,radii,categories);await query("UPDATE stores SET pois_json=$1,analysis_json=$2,status='分析完成',error_message=NULL,updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND created_by=$5",[JSON.stringify(pois),JSON.stringify(analysis),store.id,tenantId,userId])}catch(error){if(isQuotaPauseError(error)){await query("UPDATE jobs SET status='额度暂停',control='auto',current_store='',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[jobId,tenantId,userId]);await taskQueue.add("analyze-batch",{jobId,tenantId,userId},{attempts:1,delay:quotaResumeDelay()});break}await query("UPDATE stores SET status='分析失败',error_message=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[error instanceof Error?error.message:"分析失败",store.id,tenantId,userId])}await refreshJob(jobId,tenantId,userId,"analysis")}
  const counts=await refreshJob(jobId,tenantId,userId,"analysis"),state=await ownerJob(jobId,tenantId,userId);if(state?.control==="run")await query("UPDATE jobs SET status=$1,control='idle',current_store='',updated_at=NOW() WHERE id=$2 AND tenant_id=$3 AND created_by=$4",[counts.failed?"部分完成":"已完成",jobId,tenantId,userId]);return counts;
}

async function processJob(job:Job){
  let tenantId=Number(job.data.tenantId||0),userId=Number(job.data.userId||0);
  if(!userId&&job.data.jobId){const legacy=(await query<Row>("SELECT tenant_id,created_by FROM jobs WHERE id=$1",[job.data.jobId])).rows[0];tenantId=Number(legacy?.tenant_id||tenantId);userId=Number(legacy?.created_by||0)}
  if(!userId&&job.data.storeId){const legacy=(await query<Row>("SELECT tenant_id,created_by FROM stores WHERE id=$1",[job.data.storeId])).rows[0];tenantId=Number(legacy?.tenant_id||tenantId);userId=Number(legacy?.created_by||0)}
  if(!tenantId||!userId)throw new Error("任务缺少账号归属信息");
  if(job.name==="match-batch")return matchBatch(Number(job.data.jobId),Number(tenantId),Number(userId));
  if(job.name==="analyze-batch")return analyzeBatch(Number(job.data.jobId),Number(tenantId),Number(userId));
  if(job.name==="analyze-single"){const {storeId,categories,radii}=job.data,store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[storeId,tenantId,userId])).rows[0];if(!store)throw new Error("门店不存在");const pois=await searchPois(store,categories,radii),analysis=createAnalysis(store,pois,radii,categories);await query("UPDATE stores SET pois_json=$1,analysis_json=$2,status='分析完成',updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND created_by=$5",[JSON.stringify(pois),JSON.stringify(analysis),storeId,tenantId,userId]);return {pois,analysis}}
  if(job.name==="ai-single"){const {storeId,radii,activityConfig}=job.data,store=(await query<Row>("SELECT * FROM stores WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[storeId,tenantId,userId])).rows[0];if(!store)throw new Error("门店不存在");return generateAi(Number(tenantId),Number(userId),"single",[aggregateStore("门店A",(store.pois_json||[]) as Poi[],radii)],store.job_id?Number(store.job_id):null,Number(storeId),[Number(storeId)],{activityConfig:activityConfig||{activity_name:"门店亲子活动分析",objective:"识别妈妈带孩子家庭与活动触达场景",activity_time:"待业务确认"}})}
  if(job.name==="ai-comparison"){const {jobId,storeIds,radii}=job.data;if(!await ownerJob(Number(jobId),Number(tenantId),Number(userId)))throw new Error("任务不存在");const rows=(await query<Row>("SELECT * FROM stores WHERE tenant_id=$1 AND created_by=$2 AND job_id=$3 AND id=ANY($4::bigint[])",[tenantId,userId,jobId,storeIds])).rows,ordered=(storeIds as number[]).map(id=>rows.find(row=>Number(row.id)===Number(id)));if(ordered.some(row=>!row))throw new Error("部分门店不存在");return generateAi(Number(tenantId),Number(userId),"comparison",ordered.map((row,index)=>aggregateStore(`门店${String.fromCharCode(65+index)}`,(row?.pois_json||[]) as Poi[],radii)),Number(jobId),null,storeIds)}
  if(job.name==="ai-export-batch")return processAiExport(Number(job.data.exportId),tenantId,userId);
  if(job.name==="discover-brand-stores")return processDiscoveryJob(Number(job.data.jobId),tenantId,userId);
  if(job.name==="brand-library-export")return processBrandExport(Number(job.data.exportId),tenantId,userId);
  throw new Error(`未知任务类型：${job.name}`);
}

const worker=new Worker("store-analysis",processJob,{connection:redisConnection,concurrency:Math.max(1,Math.min(5,Number(process.env.WORKER_CONCURRENCY||3)))});worker.on("completed",job=>console.log(JSON.stringify({event:"job_completed",id:job.id,name:job.name})));worker.on("failed",(job,error)=>{console.error(JSON.stringify({event:"job_failed",id:job?.id,name:job?.name,error:error.message}));if(job?.name==="ai-export-batch"&&job.data?.exportId)void query("UPDATE ai_export_jobs SET status='failed',error_message=$1,current_store='',completed_at=NOW(),updated_at=NOW() WHERE id=$2",[error.message,job.data.exportId]);else if(job?.name==="brand-library-export"&&job.data?.exportId)void query("UPDATE brand_export_jobs SET status='failed',error_message=$1,completed_at=NOW(),updated_at=NOW() WHERE id=$2",[error.message,job.data.exportId]);else if(job?.name==="discover-brand-stores"&&job.data?.jobId)void query("UPDATE brand_discovery_jobs SET status='任务执行失败',control='idle',error_message=$1,current_region='',updated_at=NOW() WHERE id=$2",[error.message,job.data.jobId]);else if(job?.data?.jobId&&job.data?.tenantId&&job.data?.userId)void query("UPDATE jobs SET status='任务执行失败',control='idle',current_store='',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND created_by=$3",[job.data.jobId,job.data.tenantId,job.data.userId])});console.log("Queue worker started");
async function stop(){await worker.close();process.exit(0)}process.on("SIGTERM",stop);process.on("SIGINT",stop);
