CREATE OR REPLACE FUNCTION brand_policy_reason(brand text, name text, poi_id text, manual text, poi_type text, codes text, raw jsonb) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
 WITH evidence AS (SELECT ailingshi_normalize(name) AS n,
 COALESCE(poi_type,'') || ';' || COALESCE(raw->>'tag','') || ';' || COALESCE(raw#>>'{business,tag}','') || ';' || COALESCE(raw#>>'{business,rectag}','') || ';' || COALESCE(raw#>>'{business,keytag}','') AS tags,
 COALESCE(raw->>'tag','') || ';' || COALESCE(raw#>>'{business,tag}','') || ';' || COALESCE(raw#>>'{business,rectag}','') || ';' || COALESCE(raw#>>'{business,keytag}','') AS business_tags,
 COALESCE(poi_type,'') AS pt,
 regexp_replace(COALESCE(codes,''),'[[:space:]]','','g') AS c), flags AS (
 SELECT *, (tags ~ '零食|超市|购物' OR c ~ '(^|[|;,])06[0-9]{4}([|;,]|$)') AS retail,
 tags ~ '零食' AS snack_evidence,
 business_tags ~ '(^|[;,])零食([;,]|$)' AS business_snack FROM evidence)
 SELECT CASE
 WHEN btrim(COALESCE(poi_id,''))<>'' AND manual='exclude' THEN '按 POI ID 人工排除'
 WHEN n ~ '暂停营业|装修中|正在装修|停业|歇业|已关闭|未开业|即将开业|待开业|筹备中|施工中' THEN '标注暂停营业、装修中或未开业，非当前营业门店'
 WHEN n ~ '\([^()]*(仓库|仓)\)' THEN '名称明确为仓库，非营业门店'
 WHEN split_part(n,'(',1) ~ '蛋糕|糕饼|西饼|酱卤|卤味|卤菜|熟食|餐厅|餐馆|饭店|小吃|快餐|火锅|烧烤|麻辣烫|炸鸡|汉堡|奶茶|咖啡|面馆|浇面|米粉|足道|足疗|足浴|按摩|推拿|生鲜超市|酒店|宾馆|药房|药店|服装|理发|美容|公司$|仓库|配送中心|仓配中心|供应链中心|办事处|甜品|烘焙|民宿|公寓$|外卖柜|网吧|KTV|停车场|充电站|动物医院|物流基地|面试中心|菜鸟驿站|台球(俱乐部)?$|棋牌(俱乐部|室)?$|洗衣(店)?$|果业$|眼镜店$' THEN '名称主体明确为餐饮、足浴、生鲜、仓库等非目标业态'
 WHEN brand='爱零食' AND manual<>'accept' AND n ~ '^(爱零食的喵|我爱零食|最爱零食|爱零食小屋)' THEN '相似名称，不按目标品牌收录'
 WHEN tags ~ '蛋糕|糕饼|西饼|烘焙|甜品' AND NOT snack_evidence THEN '分类或标签明确为蛋糕／烘焙等非目标业态'
 WHEN tags ~ '中餐厅|西餐厅|快餐厅|小吃店|面馆|粉面店|火锅店|烧烤店|奶茶店|咖啡厅|茶馆|洗浴|足疗|足道|足浴|按摩|推拿|养生馆|美容院|美发店|理发店|药店|药房|生鲜超市|生鲜店|生鲜市场|农贸市场|菜市场|水果店|蔬菜店|酒店|宾馆|民宿|仓库|物流' AND NOT snack_evidence THEN '高德具体分类或标签明确为餐饮、足浴、生鲜等非目标业态'
 WHEN btrim(COALESCE(poi_id,''))='' THEN '缺少 POI ID，待核验'
 WHEN manual<>'accept' AND NOT (CASE brand WHEN '吖嘀吖嘀' THEN (n ~ '^(吖嘀吖嘀)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(吖嘀吖嘀)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(吖嘀吖嘀)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '好想来' THEN (n ~ '^(好想来|好想来品牌零食|好想来零食乐园)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(好想来|好想来品牌零食|好想来零食乐园)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(好想来|好想来品牌零食|好想来零食乐园)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '戴永红' THEN (n ~ '^(戴永红)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(戴永红)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(戴永红)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '来伊份' THEN (n ~ '^(来伊份)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(来伊份)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(来伊份)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '来优品' THEN (n ~ '^(来优品|来优品品牌零食|来优品零食乐园)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(来优品|来优品品牌零食|来优品零食乐园)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(来优品|来优品品牌零食|来优品零食乐园)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '爱零食' THEN (n ~ '^(爱零食)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$')
WHEN '糖巢' THEN (n ~ '^(糖巢)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(糖巢)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(糖巢)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '老婆大人' THEN (n ~ '^(老婆大人)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(老婆大人)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(老婆大人)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '赵一鸣零食' THEN (n ~ '^(赵一鸣零食|赵一鸣省钱超市)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(赵一鸣零食|赵一鸣省钱超市)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(赵一鸣零食|赵一鸣省钱超市)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '陆小馋' THEN (n ~ '^(陆小馋)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(陆小馋)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(陆小馋)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '零食很忙' THEN (n ~ '^(零食很忙)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(零食很忙)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(零食很忙)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '零食悦' THEN (n ~ '^(零食悦)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(零食悦)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(零食悦)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试'))
WHEN '零食有鸣' THEN (n ~ '^(零食有鸣)(?:(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))(?:\s*\((?!\s*店\))[^()]+店\)|[^()·,]{2,}店(?:\s*\((?!\s*店\))[^()]+店\))?)?|\((?!\s*店\))[^()]+店\))?$' OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND split_part(n,'(',1) !~ '台球|棋牌|游乐|洗衣|家纺|家具|烟花|文具|眼镜|培训|果业|喜铺|喜礼|婚品|拖鞋|直播|代买|代购|朱砂' AND n ~ '^(零食有鸣)[^()·,]{2,}店$') OR (business_snack AND (pt<>'' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND n ~ '^[^()]+\([^()]+\)$' AND split_part(n,'(',1) ~ '^(零食有鸣)(?:·?(零食|零食店|零食铺|零食超市|零食省钱超市|量贩零食|量贩零食店|量贩零食超市|零食量贩|零食量贩店|零食专卖店|新一代国民零食|休闲食品|超市|批发超市|硬折扣超市|省钱超市|折扣超市|购物超市|生活超市|便利店|便利超市|量贩便利店))?$' AND split_part(split_part(n,'(',2),')',1) !~ '暂停营业|装修中|停业|歇业|已关闭|仓库|仓$|客服|公司|总部|配送|办公|招商|面试')) ELSE FALSE END) THEN '名称未匹配品牌完整结构，待核验'
 WHEN (tags ~ '蛋糕|糕饼|西饼|烘焙|甜品|中餐厅|西餐厅|快餐厅|小吃店|面馆|粉面店|火锅店|烧烤店|奶茶店|咖啡厅|茶馆|洗浴|足疗|足道|足浴|按摩|推拿|养生馆|美容院|美发店|理发店|药店|药房|生鲜超市|生鲜店|生鲜市场|农贸市场|菜市场|水果店|蔬菜店|酒店|宾馆|民宿|仓库|物流|餐饮|住宿|医疗|公司企业|交通设施|科教文化|商务住宅' OR c ~ '(^|[|;,])(?!06[0-9]{4}([|;,]|$)|070000([|;,]|$))[0-9]{6}([|;,]|$)') AND NOT (business_snack AND (((pt LIKE '%' || '餐饮服务;餐饮相关场所;餐饮相关' || '%' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item<>'餐饮服务;餐饮相关场所;餐饮相关' AND item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')) AND tags !~ '中餐厅|西餐厅|快餐厅|小吃店|面馆|粉面店|火锅店|烧烤店|奶茶店|咖啡厅|茶馆|洗浴|足疗|足道|足浴|按摩|推拿|养生馆|美容院|美发店|理发店|药店|药房|生鲜超市|生鲜店|生鲜市场|农贸市场|菜市场|水果店|蔬菜店|酒店|宾馆|民宿|仓库|物流' AND tags !~ '蛋糕|糕饼|西饼|烘焙|甜品') OR (tags ~ '蛋糕|糕饼|西饼|烘焙|甜品' AND business_tags !~ '蛋糕|糕饼|西饼|烘焙|甜品' AND tags !~ '中餐厅|西餐厅|快餐厅|小吃店|面馆|粉面店|火锅店|烧烤店|奶茶店|咖啡厅|茶馆|洗浴|足疗|足道|足浴|按摩|推拿|养生馆|美容院|美发店|理发店|药店|药房|生鲜超市|生鲜店|生鲜市场|农贸市场|菜市场|水果店|蔬菜店|酒店|宾馆|民宿|仓库|物流' AND pt LIKE '%糕饼店%' AND NOT EXISTS (SELECT 1 FROM unnest(string_to_array(pt,'|')) item WHERE item NOT LIKE '%糕饼店%' AND item !~ '^购物服务;(购物相关场所;购物相关场所|专卖店;专营店|便民商店/便利店;便民商店/便利店|超级市场;(超市|综合超市))$')))) THEN '高德分类或标签证据冲突，待核验'
 WHEN NOT retail THEN '缺少零食／超市／购物分类或标签证据，待核验'
 WHEN manual='accept' THEN '按 POI ID 人工确认名称，零食／超市／购物证据通过初筛' ELSE '品牌名称与零食／超市／购物证据通过初筛，未验证品牌归属' END FROM flags
$$;
CREATE OR REPLACE FUNCTION brand_policy_decision(brand text, name text, poi_id text, manual text, poi_type text, codes text, raw jsonb) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
 SELECT CASE brand_policy_reason(brand,name,poi_id,manual,poi_type,codes,raw)
 WHEN '品牌名称与零食／超市／购物证据通过初筛，未验证品牌归属' THEN '接受' WHEN '按 POI ID 人工确认名称，零食／超市／购物证据通过初筛' THEN '接受'
 WHEN '按 POI ID 人工排除' THEN '排除' WHEN '标注暂停营业、装修中或未开业，非当前营业门店' THEN '排除' WHEN '名称明确为仓库，非营业门店' THEN '排除' WHEN '名称主体明确为餐饮、足浴、生鲜、仓库等非目标业态' THEN '排除' WHEN '相似名称，不按目标品牌收录' THEN '排除' WHEN '分类或标签明确为蛋糕／烘焙等非目标业态' THEN '排除' WHEN '高德具体分类或标签明确为餐饮、足浴、生鲜等非目标业态' THEN '排除'
 ELSE '待核实' END
$$;

ALTER TABLE brand_stores ALTER COLUMN name_decision SET EXPRESSION AS
 (CASE WHEN brand_name IN ('吖嘀吖嘀','好想来','戴永红','来伊份','来优品','爱零食','糖巢','老婆大人','赵一鸣零食','陆小馋','零食很忙','零食悦','零食有鸣') THEN brand_policy_decision(brand_name,amap_name,amap_poi_id,ailingshi_override,poi_type,typecode,raw_json) ELSE '' END);
ALTER TABLE brand_stores ALTER COLUMN name_decision_reason SET EXPRESSION AS
 (CASE WHEN brand_name IN ('吖嘀吖嘀','好想来','戴永红','来伊份','来优品','爱零食','糖巢','老婆大人','赵一鸣零食','陆小馋','零食很忙','零食悦','零食有鸣') THEN brand_policy_reason(brand_name,amap_name,amap_poi_id,ailingshi_override,poi_type,typecode,raw_json) ELSE '' END);
ALTER TABLE brand_stores ALTER COLUMN library_visible SET EXPRESSION AS
 (CASE WHEN brand_name IN ('吖嘀吖嘀','好想来','戴永红','来伊份','来优品','爱零食','糖巢','老婆大人','赵一鸣零食','陆小馋','零食很忙','零食悦','零食有鸣') THEN brand_policy_decision(brand_name,amap_name,amap_poi_id,ailingshi_override,poi_type,typecode,raw_json)='接受' ELSE (brand_name NOT IN ('良品铺子','零食优选','零食好能嗨','零食很能嗨','零食优选、零食悦、零食很能嗨','零食优选、零食悦、零食好能嗨')
    AND NOT (brand_name ~ '[、，,]' AND brand_name ~ '零食优选|零食好能嗨|零食很能嗨')
    AND split_part(split_part(regexp_replace(amap_name, '[[:space:]]', '', 'g'), '(', 1), '（', 1) <> ''
    AND split_part(split_part(regexp_replace(amap_name, '[[:space:]]', '', 'g'), '(', 1), '（', 1) !~ '酱卤|卤味|卤菜|熟食|餐厅|餐馆|饭店|饭庄|小吃|快餐|火锅|烧烤|麻辣烫|炸鸡|汉堡|奶茶|咖啡|面馆|米粉|酒店|宾馆|药房|药店|服装|理发|美容|公司$|仓库|配送中心|仓配中心|供应链中心|办事处|垂钓园|餐饮店|甜品店|奶茶店|烘焙坊|冰粉|冰沙|凉糕|民宿|公寓$|外卖柜|网吧|KTV|停车场|充电站|动物医院|物流基地|面试中心|菜鸟驿站|铁锅炖|农家饭馆'
    AND NOT ((split_part(split_part(regexp_replace(COALESCE(amap_name,''), '[[:space:]]', '', 'g'), '(', 1), '（', 1) || ';' || COALESCE(poi_type,'') || ';' || COALESCE(raw_json->>'tag','') || ';' || COALESCE(raw_json#>>'{business,tag}','') || ';' || COALESCE(raw_json#>>'{business,rectag}','') || ';' || COALESCE(raw_json#>>'{business,keytag}','')) ~ '蛋糕|糕饼|西饼' AND (split_part(split_part(regexp_replace(COALESCE(amap_name,''), '[[:space:]]', '', 'g'), '(', 1), '（', 1) || ';' || COALESCE(poi_type,'') || ';' || COALESCE(raw_json->>'tag','') || ';' || COALESCE(raw_json#>>'{business,tag}','') || ';' || COALESCE(raw_json#>>'{business,rectag}','') || ';' || COALESCE(raw_json#>>'{business,keytag}','')) !~ '零食|超市|日杂店')) END);
ALTER TABLE brand_stores ALTER COLUMN needs_review SET EXPRESSION AS
 (CASE WHEN brand_name IN ('吖嘀吖嘀','好想来','戴永红','来伊份','来优品','爱零食','糖巢','老婆大人','赵一鸣零食','陆小馋','零食很忙','零食悦','零食有鸣') THEN brand_policy_decision(brand_name,amap_name,amap_poi_id,ailingshi_override,poi_type,typecode,raw_json)='待核实' ELSE FALSE END);
CREATE INDEX IF NOT EXISTS idx_brand_policy_review ON brand_stores(tenant_id,name_decision,id) WHERE deleted_at IS NULL;
UPDATE brand_dashboard_snapshots SET invalidated_at=NOW();
UPDATE brand_region_cache c SET store_count=(SELECT count(*) FROM brand_stores s WHERE s.tenant_id=c.tenant_id AND s.brand_name=c.brand_name AND s.province=c.province AND s.city=c.city AND s.library_visible AND s.deleted_at IS NULL);
ANALYZE brand_stores;
